/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import BackupJob from './model/BackupJob';
import BackupSchedule from './model/BackupSchedule';
import BackupScheduleBase from './model/BackupScheduleBase';
import BackupScheduleBaseDevicesapplicable from './model/BackupScheduleBaseDevicesapplicable';
import BackupScheduleDaily from './model/BackupScheduleDaily';
import BackupScheduleES from './model/BackupScheduleES';
import BackupScheduleESBase from './model/BackupScheduleESBase';
import BackupScheduleMonthly from './model/BackupScheduleMonthly';
import BackupScheduleOnce from './model/BackupScheduleOnce';
import BackupScheduleResponse from './model/BackupScheduleResponse';
import BackupScheduleResponseBase from './model/BackupScheduleResponseBase';
import BackupScheduleUpdate from './model/BackupScheduleUpdate';
import BackupScheduleUpdateBase from './model/BackupScheduleUpdateBase';
import BackupScheduleUpdateES from './model/BackupScheduleUpdateES';
import BackupScheduleUpdateESBase from './model/BackupScheduleUpdateESBase';
import BackupScheduleUpdateForDailyFrequency from './model/BackupScheduleUpdateForDailyFrequency';
import BackupScheduleUpdateForMonthlyFrequency from './model/BackupScheduleUpdateForMonthlyFrequency';
import BackupScheduleUpdateForOnceFrequency from './model/BackupScheduleUpdateForOnceFrequency';
import BackupScheduleUpdateForWeeklyFrequency from './model/BackupScheduleUpdateForWeeklyFrequency';
import BackupScheduleWeekly from './model/BackupScheduleWeekly';
import Body from './model/Body';
import Body1 from './model/Body1';
import Body10 from './model/Body10';
import Body11 from './model/Body11';
import Body12 from './model/Body12';
import Body13 from './model/Body13';
import Body14 from './model/Body14';
import Body15 from './model/Body15';
import Body16 from './model/Body16';
import Body17 from './model/Body17';
import Body18 from './model/Body18';
import Body19 from './model/Body19';
import Body2 from './model/Body2';
import Body20 from './model/Body20';
import Body21 from './model/Body21';
import Body22 from './model/Body22';
import Body23 from './model/Body23';
import Body24 from './model/Body24';
import Body25 from './model/Body25';
import Body26 from './model/Body26';
import Body27 from './model/Body27';
import Body28 from './model/Body28';
import Body29 from './model/Body29';
import Body3 from './model/Body3';
import Body30 from './model/Body30';
import Body31 from './model/Body31';
import Body32 from './model/Body32';
import Body33 from './model/Body33';
import Body34 from './model/Body34';
import Body35 from './model/Body35';
import Body36 from './model/Body36';
import Body37 from './model/Body37';
import Body38 from './model/Body38';
import Body39 from './model/Body39';
import Body4 from './model/Body4';
import Body40 from './model/Body40';
import Body41 from './model/Body41';
import Body42 from './model/Body42';
import Body43 from './model/Body43';
import Body44 from './model/Body44';
import Body45 from './model/Body45';
import Body46 from './model/Body46';
import Body5 from './model/Body5';
import Body6 from './model/Body6';
import Body7 from './model/Body7';
import Body8 from './model/Body8';
import Body9 from './model/Body9';
import Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress from './model/Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress';
import Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddressIpaddress from './model/Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddressIpaddress';
import Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpserverinterface10tcpserverinterfacepactcpserverinterfaceconfigurationlocaladdressTcpserverinterface10localaddress from './model/Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpserverinterface10tcpserverinterfacepactcpserverinterfaceconfigurationlocaladdressTcpserverinterface10localaddress';
import Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value from './model/Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value';
import ErrorDescription from './model/ErrorDescription';
import ForwardingDomain from './model/ForwardingDomain';
import ForwardingDomainFcport from './model/ForwardingDomainFcport';
import ForwardingDomainForwardingconstruct from './model/ForwardingDomainForwardingconstruct';
import ForwardingDomainName from './model/ForwardingDomainName';
import GenericRepresentation from './model/GenericRepresentation';
import GenericRepresentationConsequentactionlist from './model/GenericRepresentationConsequentactionlist';
import GenericRepresentationInputvaluelist from './model/GenericRepresentationInputvaluelist';
import GenericRepresentationResponsevaluelist from './model/GenericRepresentationResponsevaluelist';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse20010 from './model/InlineResponse20010';
import InlineResponse20010Latestrestoresmetadataofdevice from './model/InlineResponse20010Latestrestoresmetadataofdevice';
import InlineResponse20011 from './model/InlineResponse20011';
import InlineResponse20011Devicerestoremetadata from './model/InlineResponse20011Devicerestoremetadata';
import InlineResponse20012 from './model/InlineResponse20012';
import InlineResponse20013 from './model/InlineResponse20013';
import InlineResponse20013Coremodel14controlconstruct from './model/InlineResponse20013Coremodel14controlconstruct';
import InlineResponse20014 from './model/InlineResponse20014';
import InlineResponse20014Coremodel14controlconstruct from './model/InlineResponse20014Coremodel14controlconstruct';
import InlineResponse20015 from './model/InlineResponse20015';
import InlineResponse20016 from './model/InlineResponse20016';
import InlineResponse20017 from './model/InlineResponse20017';
import InlineResponse20018 from './model/InlineResponse20018';
import InlineResponse20019 from './model/InlineResponse20019';
import InlineResponse20019Coremodel14controlconstruct from './model/InlineResponse20019Coremodel14controlconstruct';
import InlineResponse20019Coremodel14controlconstructFcport from './model/InlineResponse20019Coremodel14controlconstructFcport';
import InlineResponse20019Coremodel14controlconstructForwardingconstruct from './model/InlineResponse20019Coremodel14controlconstructForwardingconstruct';
import InlineResponse20019Coremodel14controlconstructForwardingdomain from './model/InlineResponse20019Coremodel14controlconstructForwardingdomain';
import InlineResponse20019Coremodel14controlconstructLogicalterminationpoint from './model/InlineResponse20019Coremodel14controlconstructLogicalterminationpoint';
import InlineResponse20019Coremodel14controlconstructProfilecollection from './model/InlineResponse20019Coremodel14controlconstructProfilecollection';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse20020 from './model/InlineResponse20020';
import InlineResponse20021 from './model/InlineResponse20021';
import InlineResponse20022 from './model/InlineResponse20022';
import InlineResponse20023 from './model/InlineResponse20023';
import InlineResponse20023Actionprofile10inputvaluelist from './model/InlineResponse20023Actionprofile10inputvaluelist';
import InlineResponse20024 from './model/InlineResponse20024';
import InlineResponse20025 from './model/InlineResponse20025';
import InlineResponse20026 from './model/InlineResponse20026';
import InlineResponse20027 from './model/InlineResponse20027';
import InlineResponse20027Responseprofile10fieldname from './model/InlineResponse20027Responseprofile10fieldname';
import InlineResponse20028 from './model/InlineResponse20028';
import InlineResponse20029 from './model/InlineResponse20029';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse20030 from './model/InlineResponse20030';
import InlineResponse20031 from './model/InlineResponse20031';
import InlineResponse20032 from './model/InlineResponse20032';
import InlineResponse20033 from './model/InlineResponse20033';
import InlineResponse20034 from './model/InlineResponse20034';
import InlineResponse20035 from './model/InlineResponse20035';
import InlineResponse20036 from './model/InlineResponse20036';
import InlineResponse20037 from './model/InlineResponse20037';
import InlineResponse20038 from './model/InlineResponse20038';
import InlineResponse20039 from './model/InlineResponse20039';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse20040 from './model/InlineResponse20040';
import InlineResponse20041 from './model/InlineResponse20041';
import InlineResponse20042 from './model/InlineResponse20042';
import InlineResponse20043 from './model/InlineResponse20043';
import InlineResponse20044 from './model/InlineResponse20044';
import InlineResponse20044Httpserverinterface10releaselist from './model/InlineResponse20044Httpserverinterface10releaselist';
import InlineResponse20045 from './model/InlineResponse20045';
import InlineResponse20046 from './model/InlineResponse20046';
import InlineResponse20047 from './model/InlineResponse20047';
import InlineResponse20047Tcpserverinterface10localaddress from './model/InlineResponse20047Tcpserverinterface10localaddress';
import InlineResponse20048 from './model/InlineResponse20048';
import InlineResponse20049 from './model/InlineResponse20049';
import InlineResponse2004Devicebackupmetadata from './model/InlineResponse2004Devicebackupmetadata';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse20050 from './model/InlineResponse20050';
import InlineResponse20051 from './model/InlineResponse20051';
import InlineResponse20052 from './model/InlineResponse20052';
import InlineResponse20053 from './model/InlineResponse20053';
import InlineResponse20054 from './model/InlineResponse20054';
import InlineResponse20055 from './model/InlineResponse20055';
import InlineResponse20056 from './model/InlineResponse20056';
import InlineResponse20057 from './model/InlineResponse20057';
import InlineResponse20057Tcpclientinterface10remoteaddress from './model/InlineResponse20057Tcpclientinterface10remoteaddress';
import InlineResponse20057Tcpclientinterface10remoteaddressIpaddress from './model/InlineResponse20057Tcpclientinterface10remoteaddressIpaddress';
import InlineResponse20058 from './model/InlineResponse20058';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2007Devicemetadata from './model/InlineResponse2007Devicemetadata';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2009 from './model/InlineResponse2009';
import InlineResponse2009Latestbackupsmetadataofdevice from './model/InlineResponse2009Latestbackupsmetadataofdevice';
import InlineResponse201 from './model/InlineResponse201';
import InlineResponse202 from './model/InlineResponse202';
import InlineResponse2021 from './model/InlineResponse2021';
import InlineResponse2022 from './model/InlineResponse2022';
import LogicalTerminationPoint from './model/LogicalTerminationPoint';
import OneOfBackupSchedule from './model/OneOfBackupSchedule';
import OneOfBackupScheduleUpdate from './model/OneOfBackupScheduleUpdate';
import OneOfBackupScheduleUpdateES from './model/OneOfBackupScheduleUpdateES';
import OneOfbody11 from './model/OneOfbody11';
import OneOfbody16 from './model/OneOfbody16';
import OneOfinlineResponse20012FailureTransactionLogsItems from './model/OneOfinlineResponse20012FailureTransactionLogsItems';
import OneOfinlineResponse20019Coremodel14controlconstructLogicalterminationpointLayerProtocolItems from './model/OneOfinlineResponse20019Coremodel14controlconstructLogicalterminationpointLayerProtocolItems';
import OneOfinlineResponse20019Coremodel14controlconstructProfilecollectionProfileItems from './model/OneOfinlineResponse20019Coremodel14controlconstructProfilecollectionProfileItems';
import OneOfinlineResponse20020CoreModel14profile from './model/OneOfinlineResponse20020CoreModel14profile';
import OneOflogicalTerminationPointLayerProtocolItems from './model/OneOflogicalTerminationPointLayerProtocolItems';
import V1bequeathyourdataanddieNewapplicationaddress from './model/V1bequeathyourdataanddieNewapplicationaddress';
import V1bequeathyourdataanddieNewapplicationaddressIpaddress from './model/V1bequeathyourdataanddieNewapplicationaddressIpaddress';
import V1embedyourselfOldreleaseaddress from './model/V1embedyourselfOldreleaseaddress';
import V1embedyourselfOldreleaseaddressIpaddress from './model/V1embedyourselfOldreleaseaddressIpaddress';
import V1embedyourselfRegistryofficeaddress from './model/V1embedyourselfRegistryofficeaddress';
import V1embedyourselfRegistryofficeaddressIpaddress from './model/V1embedyourselfRegistryofficeaddressIpaddress';
import V1inquirebasicauthapprovalsAddress from './model/V1inquirebasicauthapprovalsAddress';
import V1inquirebasicauthapprovalsAddressIpaddress from './model/V1inquirebasicauthapprovalsAddressIpaddress';
import V1inquireoamrequestapprovalsOamapprovaladdress from './model/V1inquireoamrequestapprovalsOamapprovaladdress';
import V1inquireoamrequestapprovalsOamapprovaladdressIpaddress from './model/V1inquireoamrequestapprovalsOamapprovaladdressIpaddress';
import V1redirectoamrequestinformationOamlogaddress from './model/V1redirectoamrequestinformationOamlogaddress';
import V1redirectoamrequestinformationOamlogaddressIpaddress from './model/V1redirectoamrequestinformationOamlogaddressIpaddress';
import V1redirectservicerequestinformationServicelogaddress from './model/V1redirectservicerequestinformationServicelogaddress';
import V1redirectservicerequestinformationServicelogaddressIpaddress from './model/V1redirectservicerequestinformationServicelogaddressIpaddress';
import V1redirecttopologychangeinformationTopologyapplicationaddress from './model/V1redirecttopologychangeinformationTopologyapplicationaddress';
import V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress from './model/V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress';
import V1registeryourselfHttpaddress from './model/V1registeryourselfHttpaddress';
import V1registeryourselfHttpaddressIpaddress from './model/V1registeryourselfHttpaddressIpaddress';
import V1registeryourselfHttpsaddress from './model/V1registeryourselfHttpsaddress';
import V1registeryourselfHttpsaddressIpaddress from './model/V1registeryourselfHttpsaddressIpaddress';
import V1registeryourselfRegistryofficeaddress from './model/V1registeryourselfRegistryofficeaddress';
import V1registeryourselfRegistryofficeaddressIpaddress from './model/V1registeryourselfRegistryofficeaddressIpaddress';
import V1updateclientFutureaddress from './model/V1updateclientFutureaddress';
import V1updateclientFutureaddressIpaddress from './model/V1updateclientFutureaddressIpaddress';
import V1updateclientofsubsequentreleaseAddress from './model/V1updateclientofsubsequentreleaseAddress';
import V1updateclientofsubsequentreleaseAddressIpaddress from './model/V1updateclientofsubsequentreleaseAddressIpaddress';
import ActionProfileApi from './api/ActionProfileApi';
import BasicServicesApi from './api/BasicServicesApi';
import CoreApi from './api/CoreApi';
import FileProfileApi from './api/FileProfileApi';
import GenericResponseProfileApi from './api/GenericResponseProfileApi';
import HttpClientApi from './api/HttpClientApi';
import HttpServerApi from './api/HttpServerApi';
import IndividualServicesApi from './api/IndividualServicesApi';
import OperationClientApi from './api/OperationClientApi';
import OperationServerApi from './api/OperationServerApi';
import TcpClientApi from './api/TcpClientApi';
import TcpServerApi from './api/TcpServerApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BackupAndRestore = require('index'); // See note below*.
* var xxxSvc = new BackupAndRestore.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BackupAndRestore.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BackupAndRestore.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BackupAndRestore.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BackupJob model constructor.
     * @property {module:model/BackupJob}
     */
    BackupJob,

    /**
     * The BackupSchedule model constructor.
     * @property {module:model/BackupSchedule}
     */
    BackupSchedule,

    /**
     * The BackupScheduleBase model constructor.
     * @property {module:model/BackupScheduleBase}
     */
    BackupScheduleBase,

    /**
     * The BackupScheduleBaseDevicesapplicable model constructor.
     * @property {module:model/BackupScheduleBaseDevicesapplicable}
     */
    BackupScheduleBaseDevicesapplicable,

    /**
     * The BackupScheduleDaily model constructor.
     * @property {module:model/BackupScheduleDaily}
     */
    BackupScheduleDaily,

    /**
     * The BackupScheduleES model constructor.
     * @property {module:model/BackupScheduleES}
     */
    BackupScheduleES,

    /**
     * The BackupScheduleESBase model constructor.
     * @property {module:model/BackupScheduleESBase}
     */
    BackupScheduleESBase,

    /**
     * The BackupScheduleMonthly model constructor.
     * @property {module:model/BackupScheduleMonthly}
     */
    BackupScheduleMonthly,

    /**
     * The BackupScheduleOnce model constructor.
     * @property {module:model/BackupScheduleOnce}
     */
    BackupScheduleOnce,

    /**
     * The BackupScheduleResponse model constructor.
     * @property {module:model/BackupScheduleResponse}
     */
    BackupScheduleResponse,

    /**
     * The BackupScheduleResponseBase model constructor.
     * @property {module:model/BackupScheduleResponseBase}
     */
    BackupScheduleResponseBase,

    /**
     * The BackupScheduleUpdate model constructor.
     * @property {module:model/BackupScheduleUpdate}
     */
    BackupScheduleUpdate,

    /**
     * The BackupScheduleUpdateBase model constructor.
     * @property {module:model/BackupScheduleUpdateBase}
     */
    BackupScheduleUpdateBase,

    /**
     * The BackupScheduleUpdateES model constructor.
     * @property {module:model/BackupScheduleUpdateES}
     */
    BackupScheduleUpdateES,

    /**
     * The BackupScheduleUpdateESBase model constructor.
     * @property {module:model/BackupScheduleUpdateESBase}
     */
    BackupScheduleUpdateESBase,

    /**
     * The BackupScheduleUpdateForDailyFrequency model constructor.
     * @property {module:model/BackupScheduleUpdateForDailyFrequency}
     */
    BackupScheduleUpdateForDailyFrequency,

    /**
     * The BackupScheduleUpdateForMonthlyFrequency model constructor.
     * @property {module:model/BackupScheduleUpdateForMonthlyFrequency}
     */
    BackupScheduleUpdateForMonthlyFrequency,

    /**
     * The BackupScheduleUpdateForOnceFrequency model constructor.
     * @property {module:model/BackupScheduleUpdateForOnceFrequency}
     */
    BackupScheduleUpdateForOnceFrequency,

    /**
     * The BackupScheduleUpdateForWeeklyFrequency model constructor.
     * @property {module:model/BackupScheduleUpdateForWeeklyFrequency}
     */
    BackupScheduleUpdateForWeeklyFrequency,

    /**
     * The BackupScheduleWeekly model constructor.
     * @property {module:model/BackupScheduleWeekly}
     */
    BackupScheduleWeekly,

    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body,

    /**
     * The Body1 model constructor.
     * @property {module:model/Body1}
     */
    Body1,

    /**
     * The Body10 model constructor.
     * @property {module:model/Body10}
     */
    Body10,

    /**
     * The Body11 model constructor.
     * @property {module:model/Body11}
     */
    Body11,

    /**
     * The Body12 model constructor.
     * @property {module:model/Body12}
     */
    Body12,

    /**
     * The Body13 model constructor.
     * @property {module:model/Body13}
     */
    Body13,

    /**
     * The Body14 model constructor.
     * @property {module:model/Body14}
     */
    Body14,

    /**
     * The Body15 model constructor.
     * @property {module:model/Body15}
     */
    Body15,

    /**
     * The Body16 model constructor.
     * @property {module:model/Body16}
     */
    Body16,

    /**
     * The Body17 model constructor.
     * @property {module:model/Body17}
     */
    Body17,

    /**
     * The Body18 model constructor.
     * @property {module:model/Body18}
     */
    Body18,

    /**
     * The Body19 model constructor.
     * @property {module:model/Body19}
     */
    Body19,

    /**
     * The Body2 model constructor.
     * @property {module:model/Body2}
     */
    Body2,

    /**
     * The Body20 model constructor.
     * @property {module:model/Body20}
     */
    Body20,

    /**
     * The Body21 model constructor.
     * @property {module:model/Body21}
     */
    Body21,

    /**
     * The Body22 model constructor.
     * @property {module:model/Body22}
     */
    Body22,

    /**
     * The Body23 model constructor.
     * @property {module:model/Body23}
     */
    Body23,

    /**
     * The Body24 model constructor.
     * @property {module:model/Body24}
     */
    Body24,

    /**
     * The Body25 model constructor.
     * @property {module:model/Body25}
     */
    Body25,

    /**
     * The Body26 model constructor.
     * @property {module:model/Body26}
     */
    Body26,

    /**
     * The Body27 model constructor.
     * @property {module:model/Body27}
     */
    Body27,

    /**
     * The Body28 model constructor.
     * @property {module:model/Body28}
     */
    Body28,

    /**
     * The Body29 model constructor.
     * @property {module:model/Body29}
     */
    Body29,

    /**
     * The Body3 model constructor.
     * @property {module:model/Body3}
     */
    Body3,

    /**
     * The Body30 model constructor.
     * @property {module:model/Body30}
     */
    Body30,

    /**
     * The Body31 model constructor.
     * @property {module:model/Body31}
     */
    Body31,

    /**
     * The Body32 model constructor.
     * @property {module:model/Body32}
     */
    Body32,

    /**
     * The Body33 model constructor.
     * @property {module:model/Body33}
     */
    Body33,

    /**
     * The Body34 model constructor.
     * @property {module:model/Body34}
     */
    Body34,

    /**
     * The Body35 model constructor.
     * @property {module:model/Body35}
     */
    Body35,

    /**
     * The Body36 model constructor.
     * @property {module:model/Body36}
     */
    Body36,

    /**
     * The Body37 model constructor.
     * @property {module:model/Body37}
     */
    Body37,

    /**
     * The Body38 model constructor.
     * @property {module:model/Body38}
     */
    Body38,

    /**
     * The Body39 model constructor.
     * @property {module:model/Body39}
     */
    Body39,

    /**
     * The Body4 model constructor.
     * @property {module:model/Body4}
     */
    Body4,

    /**
     * The Body40 model constructor.
     * @property {module:model/Body40}
     */
    Body40,

    /**
     * The Body41 model constructor.
     * @property {module:model/Body41}
     */
    Body41,

    /**
     * The Body42 model constructor.
     * @property {module:model/Body42}
     */
    Body42,

    /**
     * The Body43 model constructor.
     * @property {module:model/Body43}
     */
    Body43,

    /**
     * The Body44 model constructor.
     * @property {module:model/Body44}
     */
    Body44,

    /**
     * The Body45 model constructor.
     * @property {module:model/Body45}
     */
    Body45,

    /**
     * The Body46 model constructor.
     * @property {module:model/Body46}
     */
    Body46,

    /**
     * The Body5 model constructor.
     * @property {module:model/Body5}
     */
    Body5,

    /**
     * The Body6 model constructor.
     * @property {module:model/Body6}
     */
    Body6,

    /**
     * The Body7 model constructor.
     * @property {module:model/Body7}
     */
    Body7,

    /**
     * The Body8 model constructor.
     * @property {module:model/Body8}
     */
    Body8,

    /**
     * The Body9 model constructor.
     * @property {module:model/Body9}
     */
    Body9,

    /**
     * The Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress model constructor.
     * @property {module:model/Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress}
     */
    Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress,

    /**
     * The Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddressIpaddress model constructor.
     * @property {module:model/Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddressIpaddress}
     */
    Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddressIpaddress,

    /**
     * The Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpserverinterface10tcpserverinterfacepactcpserverinterfaceconfigurationlocaladdressTcpserverinterface10localaddress model constructor.
     * @property {module:model/Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpserverinterface10tcpserverinterfacepactcpserverinterfaceconfigurationlocaladdressTcpserverinterface10localaddress}
     */
    Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpserverinterface10tcpserverinterfacepactcpserverinterfaceconfigurationlocaladdressTcpserverinterface10localaddress,

    /**
     * The Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value model constructor.
     * @property {module:model/Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value}
     */
    Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value,

    /**
     * The ErrorDescription model constructor.
     * @property {module:model/ErrorDescription}
     */
    ErrorDescription,

    /**
     * The ForwardingDomain model constructor.
     * @property {module:model/ForwardingDomain}
     */
    ForwardingDomain,

    /**
     * The ForwardingDomainFcport model constructor.
     * @property {module:model/ForwardingDomainFcport}
     */
    ForwardingDomainFcport,

    /**
     * The ForwardingDomainForwardingconstruct model constructor.
     * @property {module:model/ForwardingDomainForwardingconstruct}
     */
    ForwardingDomainForwardingconstruct,

    /**
     * The ForwardingDomainName model constructor.
     * @property {module:model/ForwardingDomainName}
     */
    ForwardingDomainName,

    /**
     * The GenericRepresentation model constructor.
     * @property {module:model/GenericRepresentation}
     */
    GenericRepresentation,

    /**
     * The GenericRepresentationConsequentactionlist model constructor.
     * @property {module:model/GenericRepresentationConsequentactionlist}
     */
    GenericRepresentationConsequentactionlist,

    /**
     * The GenericRepresentationInputvaluelist model constructor.
     * @property {module:model/GenericRepresentationInputvaluelist}
     */
    GenericRepresentationInputvaluelist,

    /**
     * The GenericRepresentationResponsevaluelist model constructor.
     * @property {module:model/GenericRepresentationResponsevaluelist}
     */
    GenericRepresentationResponsevaluelist,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20010Latestrestoresmetadataofdevice model constructor.
     * @property {module:model/InlineResponse20010Latestrestoresmetadataofdevice}
     */
    InlineResponse20010Latestrestoresmetadataofdevice,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20011Devicerestoremetadata model constructor.
     * @property {module:model/InlineResponse20011Devicerestoremetadata}
     */
    InlineResponse20011Devicerestoremetadata,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse20013 model constructor.
     * @property {module:model/InlineResponse20013}
     */
    InlineResponse20013,

    /**
     * The InlineResponse20013Coremodel14controlconstruct model constructor.
     * @property {module:model/InlineResponse20013Coremodel14controlconstruct}
     */
    InlineResponse20013Coremodel14controlconstruct,

    /**
     * The InlineResponse20014 model constructor.
     * @property {module:model/InlineResponse20014}
     */
    InlineResponse20014,

    /**
     * The InlineResponse20014Coremodel14controlconstruct model constructor.
     * @property {module:model/InlineResponse20014Coremodel14controlconstruct}
     */
    InlineResponse20014Coremodel14controlconstruct,

    /**
     * The InlineResponse20015 model constructor.
     * @property {module:model/InlineResponse20015}
     */
    InlineResponse20015,

    /**
     * The InlineResponse20016 model constructor.
     * @property {module:model/InlineResponse20016}
     */
    InlineResponse20016,

    /**
     * The InlineResponse20017 model constructor.
     * @property {module:model/InlineResponse20017}
     */
    InlineResponse20017,

    /**
     * The InlineResponse20018 model constructor.
     * @property {module:model/InlineResponse20018}
     */
    InlineResponse20018,

    /**
     * The InlineResponse20019 model constructor.
     * @property {module:model/InlineResponse20019}
     */
    InlineResponse20019,

    /**
     * The InlineResponse20019Coremodel14controlconstruct model constructor.
     * @property {module:model/InlineResponse20019Coremodel14controlconstruct}
     */
    InlineResponse20019Coremodel14controlconstruct,

    /**
     * The InlineResponse20019Coremodel14controlconstructFcport model constructor.
     * @property {module:model/InlineResponse20019Coremodel14controlconstructFcport}
     */
    InlineResponse20019Coremodel14controlconstructFcport,

    /**
     * The InlineResponse20019Coremodel14controlconstructForwardingconstruct model constructor.
     * @property {module:model/InlineResponse20019Coremodel14controlconstructForwardingconstruct}
     */
    InlineResponse20019Coremodel14controlconstructForwardingconstruct,

    /**
     * The InlineResponse20019Coremodel14controlconstructForwardingdomain model constructor.
     * @property {module:model/InlineResponse20019Coremodel14controlconstructForwardingdomain}
     */
    InlineResponse20019Coremodel14controlconstructForwardingdomain,

    /**
     * The InlineResponse20019Coremodel14controlconstructLogicalterminationpoint model constructor.
     * @property {module:model/InlineResponse20019Coremodel14controlconstructLogicalterminationpoint}
     */
    InlineResponse20019Coremodel14controlconstructLogicalterminationpoint,

    /**
     * The InlineResponse20019Coremodel14controlconstructProfilecollection model constructor.
     * @property {module:model/InlineResponse20019Coremodel14controlconstructProfilecollection}
     */
    InlineResponse20019Coremodel14controlconstructProfilecollection,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse20020 model constructor.
     * @property {module:model/InlineResponse20020}
     */
    InlineResponse20020,

    /**
     * The InlineResponse20021 model constructor.
     * @property {module:model/InlineResponse20021}
     */
    InlineResponse20021,

    /**
     * The InlineResponse20022 model constructor.
     * @property {module:model/InlineResponse20022}
     */
    InlineResponse20022,

    /**
     * The InlineResponse20023 model constructor.
     * @property {module:model/InlineResponse20023}
     */
    InlineResponse20023,

    /**
     * The InlineResponse20023Actionprofile10inputvaluelist model constructor.
     * @property {module:model/InlineResponse20023Actionprofile10inputvaluelist}
     */
    InlineResponse20023Actionprofile10inputvaluelist,

    /**
     * The InlineResponse20024 model constructor.
     * @property {module:model/InlineResponse20024}
     */
    InlineResponse20024,

    /**
     * The InlineResponse20025 model constructor.
     * @property {module:model/InlineResponse20025}
     */
    InlineResponse20025,

    /**
     * The InlineResponse20026 model constructor.
     * @property {module:model/InlineResponse20026}
     */
    InlineResponse20026,

    /**
     * The InlineResponse20027 model constructor.
     * @property {module:model/InlineResponse20027}
     */
    InlineResponse20027,

    /**
     * The InlineResponse20027Responseprofile10fieldname model constructor.
     * @property {module:model/InlineResponse20027Responseprofile10fieldname}
     */
    InlineResponse20027Responseprofile10fieldname,

    /**
     * The InlineResponse20028 model constructor.
     * @property {module:model/InlineResponse20028}
     */
    InlineResponse20028,

    /**
     * The InlineResponse20029 model constructor.
     * @property {module:model/InlineResponse20029}
     */
    InlineResponse20029,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse20030 model constructor.
     * @property {module:model/InlineResponse20030}
     */
    InlineResponse20030,

    /**
     * The InlineResponse20031 model constructor.
     * @property {module:model/InlineResponse20031}
     */
    InlineResponse20031,

    /**
     * The InlineResponse20032 model constructor.
     * @property {module:model/InlineResponse20032}
     */
    InlineResponse20032,

    /**
     * The InlineResponse20033 model constructor.
     * @property {module:model/InlineResponse20033}
     */
    InlineResponse20033,

    /**
     * The InlineResponse20034 model constructor.
     * @property {module:model/InlineResponse20034}
     */
    InlineResponse20034,

    /**
     * The InlineResponse20035 model constructor.
     * @property {module:model/InlineResponse20035}
     */
    InlineResponse20035,

    /**
     * The InlineResponse20036 model constructor.
     * @property {module:model/InlineResponse20036}
     */
    InlineResponse20036,

    /**
     * The InlineResponse20037 model constructor.
     * @property {module:model/InlineResponse20037}
     */
    InlineResponse20037,

    /**
     * The InlineResponse20038 model constructor.
     * @property {module:model/InlineResponse20038}
     */
    InlineResponse20038,

    /**
     * The InlineResponse20039 model constructor.
     * @property {module:model/InlineResponse20039}
     */
    InlineResponse20039,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse20040 model constructor.
     * @property {module:model/InlineResponse20040}
     */
    InlineResponse20040,

    /**
     * The InlineResponse20041 model constructor.
     * @property {module:model/InlineResponse20041}
     */
    InlineResponse20041,

    /**
     * The InlineResponse20042 model constructor.
     * @property {module:model/InlineResponse20042}
     */
    InlineResponse20042,

    /**
     * The InlineResponse20043 model constructor.
     * @property {module:model/InlineResponse20043}
     */
    InlineResponse20043,

    /**
     * The InlineResponse20044 model constructor.
     * @property {module:model/InlineResponse20044}
     */
    InlineResponse20044,

    /**
     * The InlineResponse20044Httpserverinterface10releaselist model constructor.
     * @property {module:model/InlineResponse20044Httpserverinterface10releaselist}
     */
    InlineResponse20044Httpserverinterface10releaselist,

    /**
     * The InlineResponse20045 model constructor.
     * @property {module:model/InlineResponse20045}
     */
    InlineResponse20045,

    /**
     * The InlineResponse20046 model constructor.
     * @property {module:model/InlineResponse20046}
     */
    InlineResponse20046,

    /**
     * The InlineResponse20047 model constructor.
     * @property {module:model/InlineResponse20047}
     */
    InlineResponse20047,

    /**
     * The InlineResponse20047Tcpserverinterface10localaddress model constructor.
     * @property {module:model/InlineResponse20047Tcpserverinterface10localaddress}
     */
    InlineResponse20047Tcpserverinterface10localaddress,

    /**
     * The InlineResponse20048 model constructor.
     * @property {module:model/InlineResponse20048}
     */
    InlineResponse20048,

    /**
     * The InlineResponse20049 model constructor.
     * @property {module:model/InlineResponse20049}
     */
    InlineResponse20049,

    /**
     * The InlineResponse2004Devicebackupmetadata model constructor.
     * @property {module:model/InlineResponse2004Devicebackupmetadata}
     */
    InlineResponse2004Devicebackupmetadata,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse20050 model constructor.
     * @property {module:model/InlineResponse20050}
     */
    InlineResponse20050,

    /**
     * The InlineResponse20051 model constructor.
     * @property {module:model/InlineResponse20051}
     */
    InlineResponse20051,

    /**
     * The InlineResponse20052 model constructor.
     * @property {module:model/InlineResponse20052}
     */
    InlineResponse20052,

    /**
     * The InlineResponse20053 model constructor.
     * @property {module:model/InlineResponse20053}
     */
    InlineResponse20053,

    /**
     * The InlineResponse20054 model constructor.
     * @property {module:model/InlineResponse20054}
     */
    InlineResponse20054,

    /**
     * The InlineResponse20055 model constructor.
     * @property {module:model/InlineResponse20055}
     */
    InlineResponse20055,

    /**
     * The InlineResponse20056 model constructor.
     * @property {module:model/InlineResponse20056}
     */
    InlineResponse20056,

    /**
     * The InlineResponse20057 model constructor.
     * @property {module:model/InlineResponse20057}
     */
    InlineResponse20057,

    /**
     * The InlineResponse20057Tcpclientinterface10remoteaddress model constructor.
     * @property {module:model/InlineResponse20057Tcpclientinterface10remoteaddress}
     */
    InlineResponse20057Tcpclientinterface10remoteaddress,

    /**
     * The InlineResponse20057Tcpclientinterface10remoteaddressIpaddress model constructor.
     * @property {module:model/InlineResponse20057Tcpclientinterface10remoteaddressIpaddress}
     */
    InlineResponse20057Tcpclientinterface10remoteaddressIpaddress,

    /**
     * The InlineResponse20058 model constructor.
     * @property {module:model/InlineResponse20058}
     */
    InlineResponse20058,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2007Devicemetadata model constructor.
     * @property {module:model/InlineResponse2007Devicemetadata}
     */
    InlineResponse2007Devicemetadata,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse2009Latestbackupsmetadataofdevice model constructor.
     * @property {module:model/InlineResponse2009Latestbackupsmetadataofdevice}
     */
    InlineResponse2009Latestbackupsmetadataofdevice,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The InlineResponse202 model constructor.
     * @property {module:model/InlineResponse202}
     */
    InlineResponse202,

    /**
     * The InlineResponse2021 model constructor.
     * @property {module:model/InlineResponse2021}
     */
    InlineResponse2021,

    /**
     * The InlineResponse2022 model constructor.
     * @property {module:model/InlineResponse2022}
     */
    InlineResponse2022,

    /**
     * The LogicalTerminationPoint model constructor.
     * @property {module:model/LogicalTerminationPoint}
     */
    LogicalTerminationPoint,

    /**
     * The OneOfBackupSchedule model constructor.
     * @property {module:model/OneOfBackupSchedule}
     */
    OneOfBackupSchedule,

    /**
     * The OneOfBackupScheduleUpdate model constructor.
     * @property {module:model/OneOfBackupScheduleUpdate}
     */
    OneOfBackupScheduleUpdate,

    /**
     * The OneOfBackupScheduleUpdateES model constructor.
     * @property {module:model/OneOfBackupScheduleUpdateES}
     */
    OneOfBackupScheduleUpdateES,

    /**
     * The OneOfbody11 model constructor.
     * @property {module:model/OneOfbody11}
     */
    OneOfbody11,

    /**
     * The OneOfbody16 model constructor.
     * @property {module:model/OneOfbody16}
     */
    OneOfbody16,

    /**
     * The OneOfinlineResponse20012FailureTransactionLogsItems model constructor.
     * @property {module:model/OneOfinlineResponse20012FailureTransactionLogsItems}
     */
    OneOfinlineResponse20012FailureTransactionLogsItems,

    /**
     * The OneOfinlineResponse20019Coremodel14controlconstructLogicalterminationpointLayerProtocolItems model constructor.
     * @property {module:model/OneOfinlineResponse20019Coremodel14controlconstructLogicalterminationpointLayerProtocolItems}
     */
    OneOfinlineResponse20019Coremodel14controlconstructLogicalterminationpointLayerProtocolItems,

    /**
     * The OneOfinlineResponse20019Coremodel14controlconstructProfilecollectionProfileItems model constructor.
     * @property {module:model/OneOfinlineResponse20019Coremodel14controlconstructProfilecollectionProfileItems}
     */
    OneOfinlineResponse20019Coremodel14controlconstructProfilecollectionProfileItems,

    /**
     * The OneOfinlineResponse20020CoreModel14profile model constructor.
     * @property {module:model/OneOfinlineResponse20020CoreModel14profile}
     */
    OneOfinlineResponse20020CoreModel14profile,

    /**
     * The OneOflogicalTerminationPointLayerProtocolItems model constructor.
     * @property {module:model/OneOflogicalTerminationPointLayerProtocolItems}
     */
    OneOflogicalTerminationPointLayerProtocolItems,

    /**
     * The V1bequeathyourdataanddieNewapplicationaddress model constructor.
     * @property {module:model/V1bequeathyourdataanddieNewapplicationaddress}
     */
    V1bequeathyourdataanddieNewapplicationaddress,

    /**
     * The V1bequeathyourdataanddieNewapplicationaddressIpaddress model constructor.
     * @property {module:model/V1bequeathyourdataanddieNewapplicationaddressIpaddress}
     */
    V1bequeathyourdataanddieNewapplicationaddressIpaddress,

    /**
     * The V1embedyourselfOldreleaseaddress model constructor.
     * @property {module:model/V1embedyourselfOldreleaseaddress}
     */
    V1embedyourselfOldreleaseaddress,

    /**
     * The V1embedyourselfOldreleaseaddressIpaddress model constructor.
     * @property {module:model/V1embedyourselfOldreleaseaddressIpaddress}
     */
    V1embedyourselfOldreleaseaddressIpaddress,

    /**
     * The V1embedyourselfRegistryofficeaddress model constructor.
     * @property {module:model/V1embedyourselfRegistryofficeaddress}
     */
    V1embedyourselfRegistryofficeaddress,

    /**
     * The V1embedyourselfRegistryofficeaddressIpaddress model constructor.
     * @property {module:model/V1embedyourselfRegistryofficeaddressIpaddress}
     */
    V1embedyourselfRegistryofficeaddressIpaddress,

    /**
     * The V1inquirebasicauthapprovalsAddress model constructor.
     * @property {module:model/V1inquirebasicauthapprovalsAddress}
     */
    V1inquirebasicauthapprovalsAddress,

    /**
     * The V1inquirebasicauthapprovalsAddressIpaddress model constructor.
     * @property {module:model/V1inquirebasicauthapprovalsAddressIpaddress}
     */
    V1inquirebasicauthapprovalsAddressIpaddress,

    /**
     * The V1inquireoamrequestapprovalsOamapprovaladdress model constructor.
     * @property {module:model/V1inquireoamrequestapprovalsOamapprovaladdress}
     */
    V1inquireoamrequestapprovalsOamapprovaladdress,

    /**
     * The V1inquireoamrequestapprovalsOamapprovaladdressIpaddress model constructor.
     * @property {module:model/V1inquireoamrequestapprovalsOamapprovaladdressIpaddress}
     */
    V1inquireoamrequestapprovalsOamapprovaladdressIpaddress,

    /**
     * The V1redirectoamrequestinformationOamlogaddress model constructor.
     * @property {module:model/V1redirectoamrequestinformationOamlogaddress}
     */
    V1redirectoamrequestinformationOamlogaddress,

    /**
     * The V1redirectoamrequestinformationOamlogaddressIpaddress model constructor.
     * @property {module:model/V1redirectoamrequestinformationOamlogaddressIpaddress}
     */
    V1redirectoamrequestinformationOamlogaddressIpaddress,

    /**
     * The V1redirectservicerequestinformationServicelogaddress model constructor.
     * @property {module:model/V1redirectservicerequestinformationServicelogaddress}
     */
    V1redirectservicerequestinformationServicelogaddress,

    /**
     * The V1redirectservicerequestinformationServicelogaddressIpaddress model constructor.
     * @property {module:model/V1redirectservicerequestinformationServicelogaddressIpaddress}
     */
    V1redirectservicerequestinformationServicelogaddressIpaddress,

    /**
     * The V1redirecttopologychangeinformationTopologyapplicationaddress model constructor.
     * @property {module:model/V1redirecttopologychangeinformationTopologyapplicationaddress}
     */
    V1redirecttopologychangeinformationTopologyapplicationaddress,

    /**
     * The V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress model constructor.
     * @property {module:model/V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress}
     */
    V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress,

    /**
     * The V1registeryourselfHttpaddress model constructor.
     * @property {module:model/V1registeryourselfHttpaddress}
     */
    V1registeryourselfHttpaddress,

    /**
     * The V1registeryourselfHttpaddressIpaddress model constructor.
     * @property {module:model/V1registeryourselfHttpaddressIpaddress}
     */
    V1registeryourselfHttpaddressIpaddress,

    /**
     * The V1registeryourselfHttpsaddress model constructor.
     * @property {module:model/V1registeryourselfHttpsaddress}
     */
    V1registeryourselfHttpsaddress,

    /**
     * The V1registeryourselfHttpsaddressIpaddress model constructor.
     * @property {module:model/V1registeryourselfHttpsaddressIpaddress}
     */
    V1registeryourselfHttpsaddressIpaddress,

    /**
     * The V1registeryourselfRegistryofficeaddress model constructor.
     * @property {module:model/V1registeryourselfRegistryofficeaddress}
     */
    V1registeryourselfRegistryofficeaddress,

    /**
     * The V1registeryourselfRegistryofficeaddressIpaddress model constructor.
     * @property {module:model/V1registeryourselfRegistryofficeaddressIpaddress}
     */
    V1registeryourselfRegistryofficeaddressIpaddress,

    /**
     * The V1updateclientFutureaddress model constructor.
     * @property {module:model/V1updateclientFutureaddress}
     */
    V1updateclientFutureaddress,

    /**
     * The V1updateclientFutureaddressIpaddress model constructor.
     * @property {module:model/V1updateclientFutureaddressIpaddress}
     */
    V1updateclientFutureaddressIpaddress,

    /**
     * The V1updateclientofsubsequentreleaseAddress model constructor.
     * @property {module:model/V1updateclientofsubsequentreleaseAddress}
     */
    V1updateclientofsubsequentreleaseAddress,

    /**
     * The V1updateclientofsubsequentreleaseAddressIpaddress model constructor.
     * @property {module:model/V1updateclientofsubsequentreleaseAddressIpaddress}
     */
    V1updateclientofsubsequentreleaseAddressIpaddress,

    /**
    * The ActionProfileApi service constructor.
    * @property {module:api/ActionProfileApi}
    */
    ActionProfileApi,

    /**
    * The BasicServicesApi service constructor.
    * @property {module:api/BasicServicesApi}
    */
    BasicServicesApi,

    /**
    * The CoreApi service constructor.
    * @property {module:api/CoreApi}
    */
    CoreApi,

    /**
    * The FileProfileApi service constructor.
    * @property {module:api/FileProfileApi}
    */
    FileProfileApi,

    /**
    * The GenericResponseProfileApi service constructor.
    * @property {module:api/GenericResponseProfileApi}
    */
    GenericResponseProfileApi,

    /**
    * The HttpClientApi service constructor.
    * @property {module:api/HttpClientApi}
    */
    HttpClientApi,

    /**
    * The HttpServerApi service constructor.
    * @property {module:api/HttpServerApi}
    */
    HttpServerApi,

    /**
    * The IndividualServicesApi service constructor.
    * @property {module:api/IndividualServicesApi}
    */
    IndividualServicesApi,

    /**
    * The OperationClientApi service constructor.
    * @property {module:api/OperationClientApi}
    */
    OperationClientApi,

    /**
    * The OperationServerApi service constructor.
    * @property {module:api/OperationServerApi}
    */
    OperationServerApi,

    /**
    * The TcpClientApi service constructor.
    * @property {module:api/TcpClientApi}
    */
    TcpClientApi,

    /**
    * The TcpServerApi service constructor.
    * @property {module:api/TcpServerApi}
    */
    TcpServerApi
};
