/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.BackupScheduleResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BackupScheduleResponse', function() {
    it('should create an instance of BackupScheduleResponse', function() {
      // uncomment below and update the code to test BackupScheduleResponse
      //var instane = new BackupAndRestore.BackupScheduleResponse();
      //expect(instance).to.be.a(BackupAndRestore.BackupScheduleResponse);
    });

    it('should have the property lastModifiedByUser (base name: "last-modified-by-user")', function() {
      // uncomment below and update the code to test the property lastModifiedByUser
      //var instane = new BackupAndRestore.BackupScheduleResponse();
      //expect(instance).to.be();
    });

    it('should have the property lastModifiedTime (base name: "last-modified-time")', function() {
      // uncomment below and update the code to test the property lastModifiedTime
      //var instane = new BackupAndRestore.BackupScheduleResponse();
      //expect(instance).to.be();
    });

    it('should have the property lastRunTime (base name: "last-run-time")', function() {
      // uncomment below and update the code to test the property lastRunTime
      //var instane = new BackupAndRestore.BackupScheduleResponse();
      //expect(instance).to.be();
    });

  });

}));
