/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.BackupScheduleESBase();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BackupScheduleESBase', function() {
    it('should create an instance of BackupScheduleESBase', function() {
      // uncomment below and update the code to test BackupScheduleESBase
      //var instane = new BackupAndRestore.BackupScheduleESBase();
      //expect(instance).to.be.a(BackupAndRestore.BackupScheduleESBase);
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new BackupAndRestore.BackupScheduleESBase();
      //expect(instance).to.be();
    });

    it('should have the property nextRunTime (base name: "next-run-time")', function() {
      // uncomment below and update the code to test the property nextRunTime
      //var instane = new BackupAndRestore.BackupScheduleESBase();
      //expect(instance).to.be();
    });

    it('should have the property createdByUser (base name: "created-by-user")', function() {
      // uncomment below and update the code to test the property createdByUser
      //var instane = new BackupAndRestore.BackupScheduleESBase();
      //expect(instance).to.be();
    });

    it('should have the property scheduleId (base name: "schedule-id")', function() {
      // uncomment below and update the code to test the property scheduleId
      //var instane = new BackupAndRestore.BackupScheduleESBase();
      //expect(instance).to.be();
    });

    it('should have the property createdTime (base name: "created-time")', function() {
      // uncomment below and update the code to test the property createdTime
      //var instane = new BackupAndRestore.BackupScheduleESBase();
      //expect(instance).to.be();
    });

    it('should have the property cronExpression (base name: "cron-expression")', function() {
      // uncomment below and update the code to test the property cronExpression
      //var instane = new BackupAndRestore.BackupScheduleESBase();
      //expect(instance).to.be();
    });

  });

}));
