/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.Body17();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Body17', function() {
    it('should create an instance of Body17', function() {
      // uncomment below and update the code to test Body17
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be.a(BackupAndRestore.Body17);
    });

    it('should have the property registryOfficeApplication (base name: "registry-office-application")', function() {
      // uncomment below and update the code to test the property registryOfficeApplication
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property registryOfficeApplicationReleaseNumber (base name: "registry-office-application-release-number")', function() {
      // uncomment below and update the code to test the property registryOfficeApplicationReleaseNumber
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property relayServerReplacementOperation (base name: "relay-server-replacement-operation")', function() {
      // uncomment below and update the code to test the property relayServerReplacementOperation
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property relayOperationUpdateOperation (base name: "relay-operation-update-operation")', function() {
      // uncomment below and update the code to test the property relayOperationUpdateOperation
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property deregistrationOperation (base name: "deregistration-operation")', function() {
      // uncomment below and update the code to test the property deregistrationOperation
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property registryOfficeProtocol (base name: "registry-office-protocol")', function() {
      // uncomment below and update the code to test the property registryOfficeProtocol
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property registryOfficeAddress (base name: "registry-office-address")', function() {
      // uncomment below and update the code to test the property registryOfficeAddress
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property registryOfficePort (base name: "registry-office-port")', function() {
      // uncomment below and update the code to test the property registryOfficePort
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property oldReleaseProtocol (base name: "old-release-protocol")', function() {
      // uncomment below and update the code to test the property oldReleaseProtocol
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property oldReleaseAddress (base name: "old-release-address")', function() {
      // uncomment below and update the code to test the property oldReleaseAddress
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

    it('should have the property oldReleasePort (base name: "old-release-port")', function() {
      // uncomment below and update the code to test the property oldReleasePort
      //var instane = new BackupAndRestore.Body17();
      //expect(instance).to.be();
    });

  });

}));
