/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.Body18();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Body18', function() {
    it('should create an instance of Body18', function() {
      // uncomment below and update the code to test Body18
      //var instane = new BackupAndRestore.Body18();
      //expect(instance).to.be.a(BackupAndRestore.Body18);
    });

    it('should have the property serviceLogApplication (base name: "service-log-application")', function() {
      // uncomment below and update the code to test the property serviceLogApplication
      //var instane = new BackupAndRestore.Body18();
      //expect(instance).to.be();
    });

    it('should have the property serviceLogApplicationReleaseNumber (base name: "service-log-application-release-number")', function() {
      // uncomment below and update the code to test the property serviceLogApplicationReleaseNumber
      //var instane = new BackupAndRestore.Body18();
      //expect(instance).to.be();
    });

    it('should have the property serviceLogOperation (base name: "service-log-operation")', function() {
      // uncomment below and update the code to test the property serviceLogOperation
      //var instane = new BackupAndRestore.Body18();
      //expect(instance).to.be();
    });

    it('should have the property serviceLogProtocol (base name: "service-log-protocol")', function() {
      // uncomment below and update the code to test the property serviceLogProtocol
      //var instane = new BackupAndRestore.Body18();
      //expect(instance).to.be();
    });

    it('should have the property serviceLogAddress (base name: "service-log-address")', function() {
      // uncomment below and update the code to test the property serviceLogAddress
      //var instane = new BackupAndRestore.Body18();
      //expect(instance).to.be();
    });

    it('should have the property serviceLogPort (base name: "service-log-port")', function() {
      // uncomment below and update the code to test the property serviceLogPort
      //var instane = new BackupAndRestore.Body18();
      //expect(instance).to.be();
    });

  });

}));
