/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.GenericRepresentationConsequentactionlist();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GenericRepresentationConsequentactionlist', function() {
    it('should create an instance of GenericRepresentationConsequentactionlist', function() {
      // uncomment below and update the code to test GenericRepresentationConsequentactionlist
      //var instane = new BackupAndRestore.GenericRepresentationConsequentactionlist();
      //expect(instance).to.be.a(BackupAndRestore.GenericRepresentationConsequentactionlist);
    });

    it('should have the property label (base name: "label")', function() {
      // uncomment below and update the code to test the property label
      //var instane = new BackupAndRestore.GenericRepresentationConsequentactionlist();
      //expect(instance).to.be();
    });

    it('should have the property request (base name: "request")', function() {
      // uncomment below and update the code to test the property request
      //var instane = new BackupAndRestore.GenericRepresentationConsequentactionlist();
      //expect(instance).to.be();
    });

    it('should have the property inputValueList (base name: "input-value-list")', function() {
      // uncomment below and update the code to test the property inputValueList
      //var instane = new BackupAndRestore.GenericRepresentationConsequentactionlist();
      //expect(instance).to.be();
    });

    it('should have the property displayInNewBrowserWindow (base name: "display-in-new-browser-window")', function() {
      // uncomment below and update the code to test the property displayInNewBrowserWindow
      //var instane = new BackupAndRestore.GenericRepresentationConsequentactionlist();
      //expect(instance).to.be();
    });

  });

}));
