/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.InlineResponse2007Devicemetadata();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2007Devicemetadata', function() {
    it('should create an instance of InlineResponse2007Devicemetadata', function() {
      // uncomment below and update the code to test InlineResponse2007Devicemetadata
      //var instane = new BackupAndRestore.InlineResponse2007Devicemetadata();
      //expect(instance).to.be.a(BackupAndRestore.InlineResponse2007Devicemetadata);
    });

    it('should have the property mountName (base name: "mount-name")', function() {
      // uncomment below and update the code to test the property mountName
      //var instane = new BackupAndRestore.InlineResponse2007Devicemetadata();
      //expect(instance).to.be();
    });

    it('should have the property vendor (base name: "vendor")', function() {
      // uncomment below and update the code to test the property vendor
      //var instane = new BackupAndRestore.InlineResponse2007Devicemetadata();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instane = new BackupAndRestore.InlineResponse2007Devicemetadata();
      //expect(instance).to.be();
    });

    it('should have the property deviceConnectionStatus (base name: "device-connection-status")', function() {
      // uncomment below and update the code to test the property deviceConnectionStatus
      //var instane = new BackupAndRestore.InlineResponse2007Devicemetadata();
      //expect(instance).to.be();
    });

    it('should have the property lastBackupTime (base name: "last-backup-time")', function() {
      // uncomment below and update the code to test the property lastBackupTime
      //var instane = new BackupAndRestore.InlineResponse2007Devicemetadata();
      //expect(instance).to.be();
    });

    it('should have the property lastRestoreTime (base name: "last-restore-time")', function() {
      // uncomment below and update the code to test the property lastRestoreTime
      //var instane = new BackupAndRestore.InlineResponse2007Devicemetadata();
      //expect(instance).to.be();
    });

  });

}));
