/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.InlineResponse2005();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2005', function() {
    it('should create an instance of InlineResponse2005', function() {
      // uncomment below and update the code to test InlineResponse2005
      //var instane = new BackupAndRestore.InlineResponse2005();
      //expect(instance).to.be.a(BackupAndRestore.InlineResponse2005);
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new BackupAndRestore.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property basicAuthRequestIsApproved (base name: "basic-auth-request-is-approved")', function() {
      // uncomment below and update the code to test the property basicAuthRequestIsApproved
      //var instane = new BackupAndRestore.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property reasonOfObjection (base name: "reason-of-objection")', function() {
      // uncomment below and update the code to test the property reasonOfObjection
      //var instane = new BackupAndRestore.InlineResponse2005();
      //expect(instance).to.be();
    });

  });

}));
