/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.FileProfileApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FileProfileApi', function() {
    describe('getFileProfileFileDescription', function() {
      it('should call getFileProfileFileDescription successfully', function(done) {
        //uncomment below and update the code to test getFileProfileFileDescription
        //instance.getFileProfileFileDescription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFileProfileFileIdentifier', function() {
      it('should call getFileProfileFileIdentifier successfully', function(done) {
        //uncomment below and update the code to test getFileProfileFileIdentifier
        //instance.getFileProfileFileIdentifier(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFileProfileFileName', function() {
      it('should call getFileProfileFileName successfully', function(done) {
        //uncomment below and update the code to test getFileProfileFileName
        //instance.getFileProfileFileName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFileProfileOperation', function() {
      it('should call getFileProfileOperation successfully', function(done) {
        //uncomment below and update the code to test getFileProfileOperation
        //instance.getFileProfileOperation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putFileProfileFileName', function() {
      it('should call putFileProfileFileName successfully', function(done) {
        //uncomment below and update the code to test putFileProfileFileName
        //instance.putFileProfileFileName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putFileProfileOperation', function() {
      it('should call putFileProfileOperation successfully', function(done) {
        //uncomment below and update the code to test putFileProfileOperation
        //instance.putFileProfileOperation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
