/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.OperationServerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OperationServerApi', function() {
    describe('getOperationServerLifeCycleState', function() {
      it('should call getOperationServerLifeCycleState successfully', function(done) {
        //uncomment below and update the code to test getOperationServerLifeCycleState
        //instance.getOperationServerLifeCycleState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOperationServerOperationKey', function() {
      it('should call getOperationServerOperationKey successfully', function(done) {
        //uncomment below and update the code to test getOperationServerOperationKey
        //instance.getOperationServerOperationKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOperationServerOperationName', function() {
      it('should call getOperationServerOperationName successfully', function(done) {
        //uncomment below and update the code to test getOperationServerOperationName
        //instance.getOperationServerOperationName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOperationServerLifeCycleState', function() {
      it('should call putOperationServerLifeCycleState successfully', function(done) {
        //uncomment below and update the code to test putOperationServerLifeCycleState
        //instance.putOperationServerLifeCycleState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOperationServerOperationKey', function() {
      it('should call putOperationServerOperationKey successfully', function(done) {
        //uncomment below and update the code to test putOperationServerOperationKey
        //instance.putOperationServerOperationKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
