/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.OperationClientApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OperationClientApi', function() {
    describe('getOperationClientDetailedLoggingIsOn', function() {
      it('should call getOperationClientDetailedLoggingIsOn successfully', function(done) {
        //uncomment below and update the code to test getOperationClientDetailedLoggingIsOn
        //instance.getOperationClientDetailedLoggingIsOn(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOperationClientLifeCycleState', function() {
      it('should call getOperationClientLifeCycleState successfully', function(done) {
        //uncomment below and update the code to test getOperationClientLifeCycleState
        //instance.getOperationClientLifeCycleState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOperationClientOperationKey', function() {
      it('should call getOperationClientOperationKey successfully', function(done) {
        //uncomment below and update the code to test getOperationClientOperationKey
        //instance.getOperationClientOperationKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOperationClientOperationName', function() {
      it('should call getOperationClientOperationName successfully', function(done) {
        //uncomment below and update the code to test getOperationClientOperationName
        //instance.getOperationClientOperationName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOperationClientOperationalState', function() {
      it('should call getOperationClientOperationalState successfully', function(done) {
        //uncomment below and update the code to test getOperationClientOperationalState
        //instance.getOperationClientOperationalState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOperationClientDetailedLoggingIsOn', function() {
      it('should call putOperationClientDetailedLoggingIsOn successfully', function(done) {
        //uncomment below and update the code to test putOperationClientDetailedLoggingIsOn
        //instance.putOperationClientDetailedLoggingIsOn(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOperationClientOperationKey', function() {
      it('should call putOperationClientOperationKey successfully', function(done) {
        //uncomment below and update the code to test putOperationClientOperationKey
        //instance.putOperationClientOperationKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOperationClientOperationName', function() {
      it('should call putOperationClientOperationName successfully', function(done) {
        //uncomment below and update the code to test putOperationClientOperationName
        //instance.putOperationClientOperationName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
