/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BackupAndRestore);
  }
}(this, function(expect, BackupAndRestore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BackupAndRestore.TcpClientApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TcpClientApi', function() {
    describe('getTcpClientRemoteAddress', function() {
      it('should call getTcpClientRemoteAddress successfully', function(done) {
        //uncomment below and update the code to test getTcpClientRemoteAddress
        //instance.getTcpClientRemoteAddress(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTcpClientRemotePort', function() {
      it('should call getTcpClientRemotePort successfully', function(done) {
        //uncomment below and update the code to test getTcpClientRemotePort
        //instance.getTcpClientRemotePort(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTcpClientRemoteProtocol', function() {
      it('should call getTcpClientRemoteProtocol successfully', function(done) {
        //uncomment below and update the code to test getTcpClientRemoteProtocol
        //instance.getTcpClientRemoteProtocol(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putTcpClientRemoteAddress', function() {
      it('should call putTcpClientRemoteAddress successfully', function(done) {
        //uncomment below and update the code to test putTcpClientRemoteAddress
        //instance.putTcpClientRemoteAddress(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putTcpClientRemotePort', function() {
      it('should call putTcpClientRemotePort successfully', function(done) {
        //uncomment below and update the code to test putTcpClientRemotePort
        //instance.putTcpClientRemotePort(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putTcpClientRemoteProtocol', function() {
      it('should call putTcpClientRemoteProtocol successfully', function(done) {
        //uncomment below and update the code to test putTcpClientRemoteProtocol
        //instance.putTcpClientRemoteProtocol(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
