/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BackupScheduleES from './BackupScheduleES';
import BackupScheduleResponseBase from './BackupScheduleResponseBase';

/**
* The BackupScheduleResponse model module.
* @module model/BackupScheduleResponse
* @version 1.0.1
*/
export default class BackupScheduleResponse {
    /**
    * Constructs a new <code>BackupScheduleResponse</code>.
    * @alias module:model/BackupScheduleResponse
    * @class
    * @extends module:model/BackupScheduleES
    * @param status {} 
    * @param createdByUser {} 
    * @param scheduleId {} 'Auto generated Scheduler Id for the scheduled backup' 
    * @param createdTime {} 
    */

    constructor(status, createdByUser, scheduleId, createdTime) {
        this['status'] = status;
        this['created-by-user'] = createdByUser;
        this['schedule-id'] = scheduleId;
        this['created-time'] = createdTime;
    }

    /**
    * Constructs a <code>BackupScheduleResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BackupScheduleResponse} obj Optional instance to populate.
    * @return {module:model/BackupScheduleResponse} The populated <code>BackupScheduleResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupScheduleResponse();
            
            BackupScheduleES.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('last-modified-by-user')) {
                obj['last-modified-by-user'] = ApiClient.convertToType(data['last-modified-by-user'], 'String');
            }
            if (data.hasOwnProperty('last-modified-time')) {
                obj['last-modified-time'] = ApiClient.convertToType(data['last-modified-time'], 'Date');
            }
            if (data.hasOwnProperty('last-run-time')) {
                obj['last-run-time'] = ApiClient.convertToType(data['last-run-time'], 'Date');
            }
        }
        return obj;
    }

    /**
    * Only if schedule is modified
    * @member {String} last-modified-by-user
    */
    'last-modified-by-user' = undefined;
    /**
    * Only if schedule is modified
    * @member {Date} last-modified-time
    */
    'last-modified-time' = undefined;
    /**
    * Only when frequency is DAILY,WEEKLY,MONTHLY
    * @member {Date} last-run-time
    */
    'last-run-time' = undefined;




}
