/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The BackupScheduleBaseDevicesapplicable model module.
* @module model/BackupScheduleBaseDevicesapplicable
* @version 1.0.1
*/
export default class BackupScheduleBaseDevicesapplicable {
    /**
    * Constructs a new <code>BackupScheduleBaseDevicesapplicable</code>.
    * @alias module:model/BackupScheduleBaseDevicesapplicable
    * @class
    * @param vendor {String} 'Name of the vendor' 
    */

    constructor(vendor) {
        
        
        this['vendor'] = vendor;
        
    }

    /**
    * Constructs a <code>BackupScheduleBaseDevicesapplicable</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BackupScheduleBaseDevicesapplicable} obj Optional instance to populate.
    * @return {module:model/BackupScheduleBaseDevicesapplicable} The populated <code>BackupScheduleBaseDevicesapplicable</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupScheduleBaseDevicesapplicable();
                        
            
            if (data.hasOwnProperty('vendor')) {
                obj['vendor'] = ApiClient.convertToType(data['vendor'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], ['String']);
            }
        }
        return obj;
    }

    /**
    * 'Name of the vendor' 
    * @member {String} vendor
    */
    'vendor' = undefined;
    /**
    * @member {Array.<String>} model
    */
    'model' = undefined;




}
