/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BackupScheduleUpdateBase from './BackupScheduleUpdateBase';

/**
* The BackupScheduleUpdateForOnceFrequency model module.
* @module model/BackupScheduleUpdateForOnceFrequency
* @version 1.0.1
*/
export default class BackupScheduleUpdateForOnceFrequency {
    /**
    * Constructs a new <code>BackupScheduleUpdateForOnceFrequency</code>.
    * Once recurring backup schedule modification schema
    * @alias module:model/BackupScheduleUpdateForOnceFrequency
    * @class
    * @extends module:model/BackupScheduleUpdateBase
    * @param scheduleId {} 'Unique identifier of the backup schedule' 
    * @param runOnceAt {} run time of the backup schedule required only when frequency is ONCE
    */

    constructor(scheduleId, runOnceAt) {
        this['schedule-id'] = scheduleId;
        this['run-once-at'] = runOnceAt;
        
    }

    /**
    * Constructs a <code>BackupScheduleUpdateForOnceFrequency</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BackupScheduleUpdateForOnceFrequency} obj Optional instance to populate.
    * @return {module:model/BackupScheduleUpdateForOnceFrequency} The populated <code>BackupScheduleUpdateForOnceFrequency</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupScheduleUpdateForOnceFrequency();
            
            BackupScheduleUpdateBase.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('run-once-at')) {
                obj['run-once-at'] = ApiClient.convertToType(data['run-once-at'], 'Date');
            }
        }
        return obj;
    }

    /**
    * run time of the backup schedule required only when frequency is ONCE
    * @member {Date} run-once-at
    */
    'run-once-at' = undefined;

    // Implement OneOfBackupScheduleUpdate interface:
    


}
