/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BackupScheduleBase from './BackupScheduleBase';
import BackupScheduleBaseDevicesapplicable from './BackupScheduleBaseDevicesapplicable';

/**
* The BackupScheduleDaily model module.
* @module model/BackupScheduleDaily
* @version 1.0.1
*/
export default class BackupScheduleDaily {
    /**
    * Constructs a new <code>BackupScheduleDaily</code>.
    * Daily recurring backup schedule
    * @alias module:model/BackupScheduleDaily
    * @class
    * @extends module:model/BackupScheduleBase
    * @param scheduleName {} 'Name of the backup schedule' 
    * @param serverName {} 'Name of the server where the backup file shall be stored' 
    * @param devicesApplicable {} 
    * @param frequency {} 'Frequency of the backup scheduler' 
    * @param timeZone {} 'TimeZone when the backup shall be run' 
    * @param forceUpload {} 
    * @param runAtTime {} 'Time when the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    * @param startDate {} 'Start date of the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    */

    constructor(scheduleName, serverName, devicesApplicable, frequency, timeZone, forceUpload, runAtTime, startDate) {
        this['schedule-name'] = scheduleName;
        this['server-name'] = serverName;
        this['devices-applicable'] = devicesApplicable;
        this['frequency'] = frequency;
        this['time-zone'] = timeZone;
        this['force-upload'] = forceUpload;
        this['run-at-time'] = runAtTime;
        this['start-date'] = startDate;
        
    }

    /**
    * Constructs a <code>BackupScheduleDaily</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BackupScheduleDaily} obj Optional instance to populate.
    * @return {module:model/BackupScheduleDaily} The populated <code>BackupScheduleDaily</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupScheduleDaily();
            
            BackupScheduleBase.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('run-at-time')) {
                obj['run-at-time'] = ApiClient.convertToType(data['run-at-time'], 'String');
            }
            if (data.hasOwnProperty('start-date')) {
                obj['start-date'] = ApiClient.convertToType(data['start-date'], 'Date');
            }
        }
        return obj;
    }

    /**
    * 'Time when the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    * @member {String} run-at-time
    */
    'run-at-time' = undefined;
    /**
    * 'Start date of the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    * @member {Date} start-date
    */
    'start-date' = undefined;

    // Implement OneOfBackupSchedule interface:
    


}
