/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BackupScheduleBase from './BackupScheduleBase';
import BackupScheduleBaseDevicesapplicable from './BackupScheduleBaseDevicesapplicable';

/**
* The BackupScheduleWeekly model module.
* @module model/BackupScheduleWeekly
* @version 1.0.1
*/
export default class BackupScheduleWeekly {
    /**
    * Constructs a new <code>BackupScheduleWeekly</code>.
    * Weekly recurring backup schedule
    * @alias module:model/BackupScheduleWeekly
    * @class
    * @extends module:model/BackupScheduleBase
    * @param scheduleName {} 'Name of the backup schedule' 
    * @param serverName {} 'Name of the server where the backup file shall be stored' 
    * @param devicesApplicable {} 
    * @param frequency {} 'Frequency of the backup scheduler' 
    * @param timeZone {} 'TimeZone when the backup shall be run' 
    * @param forceUpload {} 
    * @param dayOfWeek {} 'Day when the backup shall be run required only when frequency is WEEKLY' 
    * @param runAtTime {} 'Time when the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    * @param startDate {} 'Start date of the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    */

    constructor(scheduleName, serverName, devicesApplicable, frequency, timeZone, forceUpload, dayOfWeek, runAtTime, startDate) {
        this['schedule-name'] = scheduleName;
        this['server-name'] = serverName;
        this['devices-applicable'] = devicesApplicable;
        this['frequency'] = frequency;
        this['time-zone'] = timeZone;
        this['force-upload'] = forceUpload;
        this['day-of-week'] = dayOfWeek;
        this['run-at-time'] = runAtTime;
        this['start-date'] = startDate;
        
    }

    /**
    * Constructs a <code>BackupScheduleWeekly</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BackupScheduleWeekly} obj Optional instance to populate.
    * @return {module:model/BackupScheduleWeekly} The populated <code>BackupScheduleWeekly</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupScheduleWeekly();
            
            BackupScheduleBase.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('day-of-week')) {
                obj['day-of-week'] = ApiClient.convertToType(data['day-of-week'], 'String');
            }
            if (data.hasOwnProperty('run-at-time')) {
                obj['run-at-time'] = ApiClient.convertToType(data['run-at-time'], 'String');
            }
            if (data.hasOwnProperty('start-date')) {
                obj['start-date'] = ApiClient.convertToType(data['start-date'], 'Date');
            }
        }
        return obj;
    }

    /**
    * 'Day when the backup shall be run required only when frequency is WEEKLY' 
    * @member {module:model/BackupScheduleWeekly.DayOfWeekEnum} day-of-week
    */
    'day-of-week' = undefined;
    /**
    * 'Time when the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    * @member {String} run-at-time
    */
    'run-at-time' = undefined;
    /**
    * 'Start date of the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    * @member {Date} start-date
    */
    'start-date' = undefined;

    // Implement OneOfBackupSchedule interface:
    

    /**
    * Allowed values for the <code>day-of-week</code> property.
    * @enum {String}
    * @readonly
    */
    static DayOfWeekEnum = {
        /**
         * value: "SUNDAY"
         * @const
         */
        "SUNDAY": "SUNDAY",
        /**
         * value: "MONDAY"
         * @const
         */
        "MONDAY": "MONDAY",
        /**
         * value: "TUESDAY"
         * @const
         */
        "TUESDAY": "TUESDAY",
        /**
         * value: "WEDNESDAY"
         * @const
         */
        "WEDNESDAY": "WEDNESDAY",
        /**
         * value: "THURSDAY"
         * @const
         */
        "THURSDAY": "THURSDAY",
        /**
         * value: "FRIDAY"
         * @const
         */
        "FRIDAY": "FRIDAY",
        /**
         * value: "SATURDAY"
         * @const
         */
        "SATURDAY": "SATURDAY"    };

}
