/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BackupScheduleUpdateBase from './BackupScheduleUpdateBase';

/**
* The BackupScheduleUpdateForWeeklyFrequency model module.
* @module model/BackupScheduleUpdateForWeeklyFrequency
* @version 1.0.1
*/
export default class BackupScheduleUpdateForWeeklyFrequency {
    /**
    * Constructs a new <code>BackupScheduleUpdateForWeeklyFrequency</code>.
    * Weekly recurring backup schedule
    * @alias module:model/BackupScheduleUpdateForWeeklyFrequency
    * @class
    * @extends module:model/BackupScheduleUpdateBase
    * @param scheduleId {} 'Unique identifier of the backup schedule' 
    * @param dayOfWeek {} 'Day when the backup shall be run required only when frequency is WEEKLY' 
    * @param runAtTime {} 'Time when the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    */

    constructor(scheduleId, dayOfWeek, runAtTime) {
        this['schedule-id'] = scheduleId;
        this['day-of-week'] = dayOfWeek;
        this['run-at-time'] = runAtTime;
        
    }

    /**
    * Constructs a <code>BackupScheduleUpdateForWeeklyFrequency</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BackupScheduleUpdateForWeeklyFrequency} obj Optional instance to populate.
    * @return {module:model/BackupScheduleUpdateForWeeklyFrequency} The populated <code>BackupScheduleUpdateForWeeklyFrequency</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupScheduleUpdateForWeeklyFrequency();
            
            BackupScheduleUpdateBase.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('day-of-week')) {
                obj['day-of-week'] = ApiClient.convertToType(data['day-of-week'], 'String');
            }
            if (data.hasOwnProperty('run-at-time')) {
                obj['run-at-time'] = ApiClient.convertToType(data['run-at-time'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'Day when the backup shall be run required only when frequency is WEEKLY' 
    * @member {module:model/BackupScheduleUpdateForWeeklyFrequency.DayOfWeekEnum} day-of-week
    */
    'day-of-week' = undefined;
    /**
    * 'Time when the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    * @member {String} run-at-time
    */
    'run-at-time' = undefined;

    // Implement OneOfBackupScheduleUpdate interface:
    

    /**
    * Allowed values for the <code>day-of-week</code> property.
    * @enum {String}
    * @readonly
    */
    static DayOfWeekEnum = {
        /**
         * value: "SUNDAY"
         * @const
         */
        "SUNDAY": "SUNDAY",
        /**
         * value: "MONDAY"
         * @const
         */
        "MONDAY": "MONDAY",
        /**
         * value: "TUESDAY"
         * @const
         */
        "TUESDAY": "TUESDAY",
        /**
         * value: "WEDNESDAY"
         * @const
         */
        "WEDNESDAY": "WEDNESDAY",
        /**
         * value: "THURSDAY"
         * @const
         */
        "THURSDAY": "THURSDAY",
        /**
         * value: "FRIDAY"
         * @const
         */
        "FRIDAY": "FRIDAY",
        /**
         * value: "SATURDAY"
         * @const
         */
        "SATURDAY": "SATURDAY"    };

}
