/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BackupSchedule from './BackupSchedule';
import BackupScheduleESBase from './BackupScheduleESBase';

/**
* The BackupScheduleES model module.
* @module model/BackupScheduleES
* @version 1.0.1
*/
export default class BackupScheduleES {
    /**
    * Constructs a new <code>BackupScheduleES</code>.
    * @alias module:model/BackupScheduleES
    * @class
    * @extends module:model/BackupSchedule
    * @param status {} 
    * @param createdByUser {} 
    * @param scheduleId {} 'Auto generated Scheduler Id for the scheduled backup' 
    * @param createdTime {} 
    */

    constructor(status, createdByUser, scheduleId, createdTime) {
        
        this['status'] = status;
        this['created-by-user'] = createdByUser;
        this['schedule-id'] = scheduleId;
        this['created-time'] = createdTime;
        
    }

    /**
    * Constructs a <code>BackupScheduleES</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BackupScheduleES} obj Optional instance to populate.
    * @return {module:model/BackupScheduleES} The populated <code>BackupScheduleES</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupScheduleES();
            
            BackupSchedule.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('next-run-time')) {
                obj['next-run-time'] = ApiClient.convertToType(data['next-run-time'], 'Date');
            }
            if (data.hasOwnProperty('created-by-user')) {
                obj['created-by-user'] = ApiClient.convertToType(data['created-by-user'], 'String');
            }
            if (data.hasOwnProperty('schedule-id')) {
                obj['schedule-id'] = ApiClient.convertToType(data['schedule-id'], 'String');
            }
            if (data.hasOwnProperty('created-time')) {
                obj['created-time'] = ApiClient.convertToType(data['created-time'], 'Date');
            }
            if (data.hasOwnProperty('cron-expression')) {
                obj['cron-expression'] = ApiClient.convertToType(data['cron-expression'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/BackupScheduleES.StatusEnum} status
    */
    'status' = undefined;
    /**
    * Only when frequency is DAILY,WEEKLY,MONTHLY
    * @member {Date} next-run-time
    */
    'next-run-time' = undefined;
    /**
    * @member {String} created-by-user
    */
    'created-by-user' = undefined;
    /**
    * 'Auto generated Scheduler Id for the scheduled backup' 
    * @member {String} schedule-id
    */
    'schedule-id' = undefined;
    /**
    * @member {Date} created-time
    */
    'created-time' = undefined;
    /**
    * cron expression evaluated in UTC Format: second hour minute hour dayOfMonth month dayOfWeek 
    * @member {String} cron-expression
    */
    'cron-expression' = undefined;



    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
        /**
         * value: "SCHEDULED"
         * @const
         */
        "SCHEDULED": "SCHEDULED",
        /**
         * value: "PAUSED"
         * @const
         */
        "PAUSED": "PAUSED",
        /**
         * value: "COMPLETED"
         * @const
         */
        "COMPLETED": "COMPLETED",
        /**
         * value: "CANCELLED"
         * @const
         */
        "CANCELLED": "CANCELLED",
        /**
         * value: "RUNNING"
         * @const
         */
        "RUNNING": "RUNNING"    };

}
