/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BackupScheduleUpdateBase from './BackupScheduleUpdateBase';

/**
* The BackupScheduleUpdateForDailyFrequency model module.
* @module model/BackupScheduleUpdateForDailyFrequency
* @version 1.0.1
*/
export default class BackupScheduleUpdateForDailyFrequency {
    /**
    * Constructs a new <code>BackupScheduleUpdateForDailyFrequency</code>.
    * Daily recurring backup schedule modification schema
    * @alias module:model/BackupScheduleUpdateForDailyFrequency
    * @class
    * @extends module:model/BackupScheduleUpdateBase
    * @param scheduleId {} 'Unique identifier of the backup schedule' 
    * @param runAtTime {} 'Time when the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    */

    constructor(scheduleId, runAtTime) {
        this['schedule-id'] = scheduleId;
        this['run-at-time'] = runAtTime;
        
    }

    /**
    * Constructs a <code>BackupScheduleUpdateForDailyFrequency</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BackupScheduleUpdateForDailyFrequency} obj Optional instance to populate.
    * @return {module:model/BackupScheduleUpdateForDailyFrequency} The populated <code>BackupScheduleUpdateForDailyFrequency</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupScheduleUpdateForDailyFrequency();
            
            BackupScheduleUpdateBase.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('run-at-time')) {
                obj['run-at-time'] = ApiClient.convertToType(data['run-at-time'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'Time when the backup shall be run required only when frequency is DAILY,WEEKLY,MONTHLY' 
    * @member {String} run-at-time
    */
    'run-at-time' = undefined;

    // Implement OneOfBackupScheduleUpdate interface:
    


}
