/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body16 model module.
* @module model/Body16
* @version 1.0.1
*/
export default class Body16 {
    /**
    * Constructs a new <code>Body16</code>.
    * @alias module:model/Body16
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body16</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body16} obj Optional instance to populate.
    * @return {module:model/Body16} The populated <code>Body16</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body16();
                        
            
        }
        return obj;
    }


    // Implement OneOfbody16 interface:
    


}
