/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value from './Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value';

/**
* The Body30 model module.
* @module model/Body30
* @version 1.0.1
*/
export default class Body30 {
    /**
    * Constructs a new <code>Body30</code>.
    * @alias module:model/Body30
    * @class
    * @param responseProfile10value {module:model/Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value} 
    */

    constructor(responseProfile10value) {
        
        
        this['response-profile-1-0:value'] = responseProfile10value;
        
    }

    /**
    * Constructs a <code>Body30</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body30} obj Optional instance to populate.
    * @return {module:model/Body30} The populated <code>Body30</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body30();
                        
            
            if (data.hasOwnProperty('response-profile-1-0:value')) {
                obj['response-profile-1-0:value'] = Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value.constructFromObject(data['response-profile-1-0:value']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Coremodel14controlconstructprofilecollectionprofileuuidresponseprofile10responseprofilepacresponseprofileconfigurationvalueResponseprofile10value} response-profile-1-0:value
    */
    'response-profile-1-0:value' = undefined;




}
