/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body27 model module.
* @module model/Body27
* @version 1.0.1
*/
export default class Body27 {
    /**
    * Constructs a new <code>Body27</code>.
    * @alias module:model/Body27
    * @class
    * @param applicationName {String} Name of application that shall be removed from configuration and application data
    * @param releaseNumber {String} Release of application that shall be removed from configuration and application data
    */

    constructor(applicationName, releaseNumber) {
        
        
        this['application-name'] = applicationName;
        this['release-number'] = releaseNumber;
        
    }

    /**
    * Constructs a <code>Body27</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body27} obj Optional instance to populate.
    * @return {module:model/Body27} The populated <code>Body27</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body27();
                        
            
            if (data.hasOwnProperty('application-name')) {
                obj['application-name'] = ApiClient.convertToType(data['application-name'], 'String');
            }
            if (data.hasOwnProperty('release-number')) {
                obj['release-number'] = ApiClient.convertToType(data['release-number'], 'String');
            }
        }
        return obj;
    }

    /**
    * Name of application that shall be removed from configuration and application data
    * @member {String} application-name
    */
    'application-name' = undefined;
    /**
    * Release of application that shall be removed from configuration and application data
    * @member {String} release-number
    */
    'release-number' = undefined;




}
