/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress from './Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress';

/**
* The Body45 model module.
* @module model/Body45
* @version 1.0.1
*/
export default class Body45 {
    /**
    * Constructs a new <code>Body45</code>.
    * @alias module:model/Body45
    * @class
    * @param tcpClientInterface10remoteAddress {module:model/Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress} 
    */

    constructor(tcpClientInterface10remoteAddress) {
        
        
        this['tcp-client-interface-1-0:remote-address'] = tcpClientInterface10remoteAddress;
        
    }

    /**
    * Constructs a <code>Body45</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body45} obj Optional instance to populate.
    * @return {module:model/Body45} The populated <code>Body45</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body45();
                        
            
            if (data.hasOwnProperty('tcp-client-interface-1-0:remote-address')) {
                obj['tcp-client-interface-1-0:remote-address'] = Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress.constructFromObject(data['tcp-client-interface-1-0:remote-address']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Coremodel14controlconstructlogicalterminationpointuuidlayerprotocol0tcpclientinterface10tcpclientinterfacepactcpclientinterfaceconfigurationremoteaddressTcpclientinterface10remoteaddress} tcp-client-interface-1-0:remote-address
    */
    'tcp-client-interface-1-0:remote-address' = undefined;




}
