/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body40 model module.
* @module model/Body40
* @version 1.0.1
*/
export default class Body40 {
    /**
    * Constructs a new <code>Body40</code>.
    * @alias module:model/Body40
    * @class
    * @param operationClientInterface10operationKey {String} 
    */

    constructor(operationClientInterface10operationKey) {
        
        
        this['operation-client-interface-1-0:operation-key'] = operationClientInterface10operationKey;
        
    }

    /**
    * Constructs a <code>Body40</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body40} obj Optional instance to populate.
    * @return {module:model/Body40} The populated <code>Body40</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body40();
                        
            
            if (data.hasOwnProperty('operation-client-interface-1-0:operation-key')) {
                obj['operation-client-interface-1-0:operation-key'] = ApiClient.convertToType(data['operation-client-interface-1-0:operation-key'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} operation-client-interface-1-0:operation-key
    */
    'operation-client-interface-1-0:operation-key' = undefined;




}
