/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body46 model module.
* @module model/Body46
* @version 1.0.1
*/
export default class Body46 {
    /**
    * Constructs a new <code>Body46</code>.
    * @alias module:model/Body46
    * @class
    * @param tcpClientInterface10remotePort {Number} 
    */

    constructor(tcpClientInterface10remotePort) {
        
        
        this['tcp-client-interface-1-0:remote-port'] = tcpClientInterface10remotePort;
        
    }

    /**
    * Constructs a <code>Body46</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body46} obj Optional instance to populate.
    * @return {module:model/Body46} The populated <code>Body46</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body46();
                        
            
            if (data.hasOwnProperty('tcp-client-interface-1-0:remote-port')) {
                obj['tcp-client-interface-1-0:remote-port'] = ApiClient.convertToType(data['tcp-client-interface-1-0:remote-port'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} tcp-client-interface-1-0:remote-port
    */
    'tcp-client-interface-1-0:remote-port' = undefined;




}
