/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1redirectoamrequestinformationOamlogaddress from './V1redirectoamrequestinformationOamlogaddress';

/**
* The Body19 model module.
* @module model/Body19
* @version 1.0.1
*/
export default class Body19 {
    /**
    * Constructs a new <code>Body19</code>.
    * @alias module:model/Body19
    * @class
    * @param oamLogApplication {String} 'Name of application that shall record the OaM requests find [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-ol-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]' 
    * @param oamLogApplicationReleaseNumber {String} 'Release of application that shall record the OaM request update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-ol-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/release-number]' 
    * @param oamLogOperation {String} 'Operation for recording the OaM requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-c-bs-ol-2-1-2-000/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]' 
    * @param oamLogProtocol {module:model/Body19.OamLogProtocolEnum} 'Protocol to be used for addressing the application that shall record the OaM requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-ol-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]' 
    * @param oamLogAddress {module:model/V1redirectoamrequestinformationOamlogaddress} 
    * @param oamLogPort {Number} 'Port of application that shall record the OaM requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-ol-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port]' 
    */

    constructor(oamLogApplication, oamLogApplicationReleaseNumber, oamLogOperation, oamLogProtocol, oamLogAddress, oamLogPort) {
        
        
        this['oam-log-application'] = oamLogApplication;
        this['oam-log-application-release-number'] = oamLogApplicationReleaseNumber;
        this['oam-log-operation'] = oamLogOperation;
        this['oam-log-protocol'] = oamLogProtocol;
        this['oam-log-address'] = oamLogAddress;
        this['oam-log-port'] = oamLogPort;
        
    }

    /**
    * Constructs a <code>Body19</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body19} obj Optional instance to populate.
    * @return {module:model/Body19} The populated <code>Body19</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body19();
                        
            
            if (data.hasOwnProperty('oam-log-application')) {
                obj['oam-log-application'] = ApiClient.convertToType(data['oam-log-application'], 'String');
            }
            if (data.hasOwnProperty('oam-log-application-release-number')) {
                obj['oam-log-application-release-number'] = ApiClient.convertToType(data['oam-log-application-release-number'], 'String');
            }
            if (data.hasOwnProperty('oam-log-operation')) {
                obj['oam-log-operation'] = ApiClient.convertToType(data['oam-log-operation'], 'String');
            }
            if (data.hasOwnProperty('oam-log-protocol')) {
                obj['oam-log-protocol'] = ApiClient.convertToType(data['oam-log-protocol'], 'String');
            }
            if (data.hasOwnProperty('oam-log-address')) {
                obj['oam-log-address'] = V1redirectoamrequestinformationOamlogaddress.constructFromObject(data['oam-log-address']);
            }
            if (data.hasOwnProperty('oam-log-port')) {
                obj['oam-log-port'] = ApiClient.convertToType(data['oam-log-port'], 'Number');
            }
        }
        return obj;
    }

    /**
    * 'Name of application that shall record the OaM requests find [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-ol-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]' 
    * @member {String} oam-log-application
    */
    'oam-log-application' = undefined;
    /**
    * 'Release of application that shall record the OaM request update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-ol-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/release-number]' 
    * @member {String} oam-log-application-release-number
    */
    'oam-log-application-release-number' = undefined;
    /**
    * 'Operation for recording the OaM requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-c-bs-ol-2-1-2-000/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]' 
    * @member {String} oam-log-operation
    */
    'oam-log-operation' = undefined;
    /**
    * 'Protocol to be used for addressing the application that shall record the OaM requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-ol-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]' 
    * @member {module:model/Body19.OamLogProtocolEnum} oam-log-protocol
    */
    'oam-log-protocol' = undefined;
    /**
    * @member {module:model/V1redirectoamrequestinformationOamlogaddress} oam-log-address
    */
    'oam-log-address' = undefined;
    /**
    * 'Port of application that shall record the OaM requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-ol-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port]' 
    * @member {Number} oam-log-port
    */
    'oam-log-port' = undefined;



    /**
    * Allowed values for the <code>oam-log-protocol</code> property.
    * @enum {String}
    * @readonly
    */
    static OamLogProtocolEnum = {
        /**
         * value: "HTTP"
         * @const
         */
        "HTTP": "HTTP",
        /**
         * value: "HTTPS"
         * @const
         */
        "HTTPS": "HTTPS"    };

}
