/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body39 model module.
* @module model/Body39
* @version 1.0.1
*/
export default class Body39 {
    /**
    * Constructs a new <code>Body39</code>.
    * @alias module:model/Body39
    * @class
    * @param operationClientInterface10operationName {String} 
    */

    constructor(operationClientInterface10operationName) {
        
        
        this['operation-client-interface-1-0:operation-name'] = operationClientInterface10operationName;
        
    }

    /**
    * Constructs a <code>Body39</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body39} obj Optional instance to populate.
    * @return {module:model/Body39} The populated <code>Body39</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body39();
                        
            
            if (data.hasOwnProperty('operation-client-interface-1-0:operation-name')) {
                obj['operation-client-interface-1-0:operation-name'] = ApiClient.convertToType(data['operation-client-interface-1-0:operation-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} operation-client-interface-1-0:operation-name
    */
    'operation-client-interface-1-0:operation-name' = undefined;




}
