/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1inquirebasicauthapprovalsAddress from './V1inquirebasicauthapprovalsAddress';

/**
* The Body26 model module.
* @module model/Body26
* @version 1.0.1
*/
export default class Body26 {
    /**
    * Constructs a new <code>Body26</code>.
    * @alias module:model/Body26
    * @class
    * @param applicationName {String} 'Name of the application that approves the BasicAuth requests find or update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-aa-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]' 
    * @param releaseNumber {String} 'Release of the application that approves the BasicAuth requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-aa-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/release-number]' 
    * @param operationName {String} 'Operation for approving the BasicAuth requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-c-bs-aa-2-1-2-000/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]' 
    * @param protocol {module:model/Body26.ProtocolEnum} 'Protocol to be used for addressing the application that approves the BasicAuth requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-aa-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]' 
    * @param address {module:model/V1inquirebasicauthapprovalsAddress} 
    * @param port {Number} 'Port of the application that approves the BasicAuth requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-aa-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port]' 
    */

    constructor(applicationName, releaseNumber, operationName, protocol, address, port) {
        
        
        this['application-name'] = applicationName;
        this['release-number'] = releaseNumber;
        this['operation-name'] = operationName;
        this['protocol'] = protocol;
        this['address'] = address;
        this['port'] = port;
        
    }

    /**
    * Constructs a <code>Body26</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body26} obj Optional instance to populate.
    * @return {module:model/Body26} The populated <code>Body26</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body26();
                        
            
            if (data.hasOwnProperty('application-name')) {
                obj['application-name'] = ApiClient.convertToType(data['application-name'], 'String');
            }
            if (data.hasOwnProperty('release-number')) {
                obj['release-number'] = ApiClient.convertToType(data['release-number'], 'String');
            }
            if (data.hasOwnProperty('operation-name')) {
                obj['operation-name'] = ApiClient.convertToType(data['operation-name'], 'String');
            }
            if (data.hasOwnProperty('protocol')) {
                obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = V1inquirebasicauthapprovalsAddress.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
        }
        return obj;
    }

    /**
    * 'Name of the application that approves the BasicAuth requests find or update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-aa-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]' 
    * @member {String} application-name
    */
    'application-name' = undefined;
    /**
    * 'Release of the application that approves the BasicAuth requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-aa-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/release-number]' 
    * @member {String} release-number
    */
    'release-number' = undefined;
    /**
    * 'Operation for approving the BasicAuth requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-c-bs-aa-2-1-2-000/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]' 
    * @member {String} operation-name
    */
    'operation-name' = undefined;
    /**
    * 'Protocol to be used for addressing the application that approves the BasicAuth requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-aa-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]' 
    * @member {module:model/Body26.ProtocolEnum} protocol
    */
    'protocol' = undefined;
    /**
    * @member {module:model/V1inquirebasicauthapprovalsAddress} address
    */
    'address' = undefined;
    /**
    * 'Port of the application that approves the BasicAuth requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-aa-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port]' 
    * @member {Number} port
    */
    'port' = undefined;



    /**
    * Allowed values for the <code>protocol</code> property.
    * @enum {String}
    * @readonly
    */
    static ProtocolEnum = {
        /**
         * value: "HTTP"
         * @const
         */
        "HTTP": "HTTP",
        /**
         * value: "HTTPS"
         * @const
         */
        "HTTPS": "HTTPS"    };

}
