/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1redirectservicerequestinformationServicelogaddress from './V1redirectservicerequestinformationServicelogaddress';

/**
* The Body18 model module.
* @module model/Body18
* @version 1.0.1
*/
export default class Body18 {
    /**
    * Constructs a new <code>Body18</code>.
    * @alias module:model/Body18
    * @class
    * @param serviceLogApplication {String} 'Name of application that shall record the service requests find [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-eatl-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]' 
    * @param serviceLogApplicationReleaseNumber {String} 'Release of application that shall record the service requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-eatl-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/release-number]' 
    * @param serviceLogOperation {String} 'Operation for recording the service requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-c-bs-eatl-2-1-2-000/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]' 
    * @param serviceLogProtocol {module:model/Body18.ServiceLogProtocolEnum} 'Protocol to be used for addressing the application that shall record the service requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-eatl-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]' 
    * @param serviceLogAddress {module:model/V1redirectservicerequestinformationServicelogaddress} 
    * @param serviceLogPort {Number} 'Port of application that shall record the service requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-eatl-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port]' 
    */

    constructor(serviceLogApplication, serviceLogApplicationReleaseNumber, serviceLogOperation, serviceLogProtocol, serviceLogAddress, serviceLogPort) {
        
        
        this['service-log-application'] = serviceLogApplication;
        this['service-log-application-release-number'] = serviceLogApplicationReleaseNumber;
        this['service-log-operation'] = serviceLogOperation;
        this['service-log-protocol'] = serviceLogProtocol;
        this['service-log-address'] = serviceLogAddress;
        this['service-log-port'] = serviceLogPort;
        
    }

    /**
    * Constructs a <code>Body18</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body18} obj Optional instance to populate.
    * @return {module:model/Body18} The populated <code>Body18</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body18();
                        
            
            if (data.hasOwnProperty('service-log-application')) {
                obj['service-log-application'] = ApiClient.convertToType(data['service-log-application'], 'String');
            }
            if (data.hasOwnProperty('service-log-application-release-number')) {
                obj['service-log-application-release-number'] = ApiClient.convertToType(data['service-log-application-release-number'], 'String');
            }
            if (data.hasOwnProperty('service-log-operation')) {
                obj['service-log-operation'] = ApiClient.convertToType(data['service-log-operation'], 'String');
            }
            if (data.hasOwnProperty('service-log-protocol')) {
                obj['service-log-protocol'] = ApiClient.convertToType(data['service-log-protocol'], 'String');
            }
            if (data.hasOwnProperty('service-log-address')) {
                obj['service-log-address'] = V1redirectservicerequestinformationServicelogaddress.constructFromObject(data['service-log-address']);
            }
            if (data.hasOwnProperty('service-log-port')) {
                obj['service-log-port'] = ApiClient.convertToType(data['service-log-port'], 'Number');
            }
        }
        return obj;
    }

    /**
    * 'Name of application that shall record the service requests find [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-eatl-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]' 
    * @member {String} service-log-application
    */
    'service-log-application' = undefined;
    /**
    * 'Release of application that shall record the service requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-c-eatl-2-1-2-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/release-number]' 
    * @member {String} service-log-application-release-number
    */
    'service-log-application-release-number' = undefined;
    /**
    * 'Operation for recording the service requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-c-bs-eatl-2-1-2-000/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]' 
    * @member {String} service-log-operation
    */
    'service-log-operation' = undefined;
    /**
    * 'Protocol to be used for addressing the application that shall record the service requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-eatl-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]' 
    * @member {module:model/Body18.ServiceLogProtocolEnum} service-log-protocol
    */
    'service-log-protocol' = undefined;
    /**
    * @member {module:model/V1redirectservicerequestinformationServicelogaddress} service-log-address
    */
    'service-log-address' = undefined;
    /**
    * 'Port of application that shall record the service requests update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-eatl-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port]' 
    * @member {Number} service-log-port
    */
    'service-log-port' = undefined;



    /**
    * Allowed values for the <code>service-log-protocol</code> property.
    * @enum {String}
    * @readonly
    */
    static ServiceLogProtocolEnum = {
        /**
         * value: "HTTP"
         * @const
         */
        "HTTP": "HTTP",
        /**
         * value: "HTTPS"
         * @const
         */
        "HTTPS": "HTTPS"    };

}
