/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body10 model module.
* @module model/Body10
* @version 1.0.1
*/
export default class Body10 {
    /**
    * Constructs a new <code>Body10</code>.
    * @alias module:model/Body10
    * @class
    * @param authorization {String} 'Authorization code of user, who is using the GUI' 
    */

    constructor(authorization) {
        
        
        this['Authorization'] = authorization;
        
    }

    /**
    * Constructs a <code>Body10</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body10} obj Optional instance to populate.
    * @return {module:model/Body10} The populated <code>Body10</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body10();
                        
            
            if (data.hasOwnProperty('Authorization')) {
                obj['Authorization'] = ApiClient.convertToType(data['Authorization'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'Authorization code of user, who is using the GUI' 
    * @member {String} Authorization
    */
    'Authorization' = undefined;




}
