/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body44 model module.
* @module model/Body44
* @version 1.0.1
*/
export default class Body44 {
    /**
    * Constructs a new <code>Body44</code>.
    * @alias module:model/Body44
    * @class
    * @param tcpClientInterface10remoteProtocol {module:model/Body44.TcpClientInterface10remoteProtocolEnum} 
    */

    constructor(tcpClientInterface10remoteProtocol) {
        
        
        this['tcp-client-interface-1-0:remote-protocol'] = tcpClientInterface10remoteProtocol;
        
    }

    /**
    * Constructs a <code>Body44</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body44} obj Optional instance to populate.
    * @return {module:model/Body44} The populated <code>Body44</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body44();
                        
            
            if (data.hasOwnProperty('tcp-client-interface-1-0:remote-protocol')) {
                obj['tcp-client-interface-1-0:remote-protocol'] = ApiClient.convertToType(data['tcp-client-interface-1-0:remote-protocol'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Body44.TcpClientInterface10remoteProtocolEnum} tcp-client-interface-1-0:remote-protocol
    */
    'tcp-client-interface-1-0:remote-protocol' = undefined;



    /**
    * Allowed values for the <code>tcp-client-interface-1-0:remote-protocol</code> property.
    * @enum {String}
    * @readonly
    */
    static TcpClientInterface10remoteProtocolEnum = {
        /**
         * value: "tcp-client-interface-1-0:PROTOCOL_TYPE_HTTP"
         * @const
         */
        "HTTP": "tcp-client-interface-1-0:PROTOCOL_TYPE_HTTP",
        /**
         * value: "tcp-client-interface-1-0:PROTOCOL_TYPE_HTTPS"
         * @const
         */
        "HTTPS": "tcp-client-interface-1-0:PROTOCOL_TYPE_HTTPS",
        /**
         * value: "tcp-client-interface-1-0:PROTOCOL_TYPE_NOT_YET_DEFINED"
         * @const
         */
        "NOT_YET_DEFINED": "tcp-client-interface-1-0:PROTOCOL_TYPE_NOT_YET_DEFINED"    };

}
