/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body15 model module.
* @module model/Body15
* @version 1.0.1
*/
export default class Body15 {
    /**
    * Constructs a new <code>Body15</code>.
    * @alias module:model/Body15
    * @class
    * @param mountName {String} 'Unique identifier of the network element' 
    * @param vendor {String} 'Vendor name of the network element' 
    * @param model {String} 'Model name of the network element' 
    * @param backupJobId {String} Identifier of the backup considered for restore
    */

    constructor(mountName, vendor, model, backupJobId) {
        
        
        this['mount-name'] = mountName;
        this['vendor'] = vendor;
        this['model'] = model;
        this['backup-job-id'] = backupJobId;
        
    }

    /**
    * Constructs a <code>Body15</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body15} obj Optional instance to populate.
    * @return {module:model/Body15} The populated <code>Body15</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body15();
                        
            
            if (data.hasOwnProperty('mount-name')) {
                obj['mount-name'] = ApiClient.convertToType(data['mount-name'], 'String');
            }
            if (data.hasOwnProperty('vendor')) {
                obj['vendor'] = ApiClient.convertToType(data['vendor'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('backup-job-id')) {
                obj['backup-job-id'] = ApiClient.convertToType(data['backup-job-id'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'Unique identifier of the network element' 
    * @member {String} mount-name
    */
    'mount-name' = undefined;
    /**
    * 'Vendor name of the network element' 
    * @member {String} vendor
    */
    'vendor' = undefined;
    /**
    * 'Model name of the network element' 
    * @member {String} model
    */
    'model' = undefined;
    /**
    * Identifier of the backup considered for restore
    * @member {String} backup-job-id
    */
    'backup-job-id' = undefined;




}
