/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body6 model module.
* @module model/Body6
* @version 1.0.1
*/
export default class Body6 {
    /**
    * Constructs a new <code>Body6</code>.
    * @alias module:model/Body6
    * @class
    * @param jobId {String} 'Unique identifier of the backup job' 
    */

    constructor(jobId) {
        
        
        this['job-id'] = jobId;
        
    }

    /**
    * Constructs a <code>Body6</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body6} obj Optional instance to populate.
    * @return {module:model/Body6} The populated <code>Body6</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body6();
                        
            
            if (data.hasOwnProperty('job-id')) {
                obj['job-id'] = ApiClient.convertToType(data['job-id'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'Unique identifier of the backup job' 
    * @member {String} job-id
    */
    'job-id' = undefined;




}
