/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ErrorDescription model module.
* @module model/ErrorDescription
* @version 1.0.1
*/
export default class ErrorDescription {
    /**
    * Constructs a new <code>ErrorDescription</code>.
    * @alias module:model/ErrorDescription
    * @class
    * @param code {Number} 
    * @param message {String} 
    */

    constructor(code, message) {
        
        
        this['code'] = code;
        this['message'] = message;
        
    }

    /**
    * Constructs a <code>ErrorDescription</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ErrorDescription} obj Optional instance to populate.
    * @return {module:model/ErrorDescription} The populated <code>ErrorDescription</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorDescription();
                        
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} code
    */
    'code' = undefined;
    /**
    * @member {String} message
    */
    'message' = undefined;




}
