/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ForwardingDomainName model module.
* @module model/ForwardingDomainName
* @version 1.0.1
*/
export default class ForwardingDomainName {
    /**
    * Constructs a new <code>ForwardingDomainName</code>.
    * @alias module:model/ForwardingDomainName
    * @class
    * @param valueName {String} 
    * @param value {String} 
    */

    constructor(valueName, value) {
        
        
        this['value-name'] = valueName;
        this['value'] = value;
        
    }

    /**
    * Constructs a <code>ForwardingDomainName</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ForwardingDomainName} obj Optional instance to populate.
    * @return {module:model/ForwardingDomainName} The populated <code>ForwardingDomainName</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForwardingDomainName();
                        
            
            if (data.hasOwnProperty('value-name')) {
                obj['value-name'] = ApiClient.convertToType(data['value-name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} value-name
    */
    'value-name' = undefined;
    /**
    * @member {String} value
    */
    'value' = undefined;




}
