/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ForwardingDomainForwardingconstruct from './ForwardingDomainForwardingconstruct';

/**
* The ForwardingDomain model module.
* @module model/ForwardingDomain
* @version 1.0.1
*/
export default class ForwardingDomain {
    /**
    * Constructs a new <code>ForwardingDomain</code>.
    * @alias module:model/ForwardingDomain
    * @class
    * @param uuid {String} 
    * @param forwardingConstruct {Array.<module:model/ForwardingDomainForwardingconstruct>} 
    */

    constructor(uuid, forwardingConstruct) {
        
        
        this['uuid'] = uuid;
        this['forwarding-construct'] = forwardingConstruct;
        
    }

    /**
    * Constructs a <code>ForwardingDomain</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ForwardingDomain} obj Optional instance to populate.
    * @return {module:model/ForwardingDomain} The populated <code>ForwardingDomain</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForwardingDomain();
                        
            
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('forwarding-construct')) {
                obj['forwarding-construct'] = ApiClient.convertToType(data['forwarding-construct'], [ForwardingDomainForwardingconstruct]);
            }
        }
        return obj;
    }

    /**
    * @member {String} uuid
    */
    'uuid' = undefined;
    /**
    * @member {Array.<module:model/ForwardingDomainForwardingconstruct>} forwarding-construct
    */
    'forwarding-construct' = undefined;




}
