/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ForwardingDomainFcport model module.
* @module model/ForwardingDomainFcport
* @version 1.0.1
*/
export default class ForwardingDomainFcport {
    /**
    * Constructs a new <code>ForwardingDomainFcport</code>.
    * @alias module:model/ForwardingDomainFcport
    * @class
    * @param localId {String} 
    * @param portDirection {String} 
    * @param logicalTerminationPoint {String} 
    */

    constructor(localId, portDirection, logicalTerminationPoint) {
        
        
        this['local-id'] = localId;
        this['port-direction'] = portDirection;
        this['logical-termination-point'] = logicalTerminationPoint;
        
    }

    /**
    * Constructs a <code>ForwardingDomainFcport</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ForwardingDomainFcport} obj Optional instance to populate.
    * @return {module:model/ForwardingDomainFcport} The populated <code>ForwardingDomainFcport</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForwardingDomainFcport();
                        
            
            if (data.hasOwnProperty('local-id')) {
                obj['local-id'] = ApiClient.convertToType(data['local-id'], 'String');
            }
            if (data.hasOwnProperty('port-direction')) {
                obj['port-direction'] = ApiClient.convertToType(data['port-direction'], 'String');
            }
            if (data.hasOwnProperty('logical-termination-point')) {
                obj['logical-termination-point'] = ApiClient.convertToType(data['logical-termination-point'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} local-id
    */
    'local-id' = undefined;
    /**
    * @member {String} port-direction
    */
    'port-direction' = undefined;
    /**
    * @member {String} logical-termination-point
    */
    'logical-termination-point' = undefined;




}
