/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The GenericRepresentationInputvaluelist model module.
* @module model/GenericRepresentationInputvaluelist
* @version 1.0.1
*/
export default class GenericRepresentationInputvaluelist {
    /**
    * Constructs a new <code>GenericRepresentationInputvaluelist</code>.
    * @alias module:model/GenericRepresentationInputvaluelist
    * @class
    * @param fieldName {String} 'Name of an input value required for executing the Request from [/core-model-1-4:control-construct/profile-collection/profile=dfm-1-0-0-action-p-*_/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-list=*_/name]' 
    */

    constructor(fieldName) {
        
        
        this['field-name'] = fieldName;
        
    }

    /**
    * Constructs a <code>GenericRepresentationInputvaluelist</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GenericRepresentationInputvaluelist} obj Optional instance to populate.
    * @return {module:model/GenericRepresentationInputvaluelist} The populated <code>GenericRepresentationInputvaluelist</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenericRepresentationInputvaluelist();
                        
            
            if (data.hasOwnProperty('field-name')) {
                obj['field-name'] = ApiClient.convertToType(data['field-name'], 'String');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'Name of an input value required for executing the Request from [/core-model-1-4:control-construct/profile-collection/profile=dfm-1-0-0-action-p-*_/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-list=*_/name]' 
    * @member {String} field-name
    */
    'field-name' = undefined;
    /**
    * 'Unit of an input value required for executing the Request from [/core-model-1-4:control-construct/profile-collection/profile=dfm-1-0-0-action-p-*_/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-list=*_/unit]' 
    * @member {String} unit
    */
    'unit' = undefined;




}
