/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The GenericRepresentationResponsevaluelist model module.
* @module model/GenericRepresentationResponsevaluelist
* @version 1.0.1
*/
export default class GenericRepresentationResponsevaluelist {
    /**
    * Constructs a new <code>GenericRepresentationResponsevaluelist</code>.
    * @alias module:model/GenericRepresentationResponsevaluelist
    * @class
    * @param fieldName {String} 'Field name from [/core-model-1-4:control-construct/profile-collection/profile=dfm-1-0-0-response-p-*_/response-profile-1-0:response-profile-pac/response-profile-capability/field-name]' 
    * @param value {String} 'Field value from [/core-model-1-4:control-construct/profile-collection/profile=dfm-1-0-0-response-p-*_/response-profile-1-0:response-profile-pac/response-profile-configuration/value]' 
    * @param datatype {String} 'Field datatype from [/core-model-1-4:control-construct/profile-collection/profile=dfm-1-0-0-response-p-*_/response-profile-1-0:response-profile-pac/response-profile-capability/datatype]' 
    */

    constructor(fieldName, value, datatype) {
        
        
        this['field-name'] = fieldName;
        this['value'] = value;
        this['datatype'] = datatype;
        
    }

    /**
    * Constructs a <code>GenericRepresentationResponsevaluelist</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GenericRepresentationResponsevaluelist} obj Optional instance to populate.
    * @return {module:model/GenericRepresentationResponsevaluelist} The populated <code>GenericRepresentationResponsevaluelist</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenericRepresentationResponsevaluelist();
                        
            
            if (data.hasOwnProperty('field-name')) {
                obj['field-name'] = ApiClient.convertToType(data['field-name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('datatype')) {
                obj['datatype'] = ApiClient.convertToType(data['datatype'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'Field name from [/core-model-1-4:control-construct/profile-collection/profile=dfm-1-0-0-response-p-*_/response-profile-1-0:response-profile-pac/response-profile-capability/field-name]' 
    * @member {String} field-name
    */
    'field-name' = undefined;
    /**
    * 'Field value from [/core-model-1-4:control-construct/profile-collection/profile=dfm-1-0-0-response-p-*_/response-profile-1-0:response-profile-pac/response-profile-configuration/value]' 
    * @member {String} value
    */
    'value' = undefined;
    /**
    * 'Field datatype from [/core-model-1-4:control-construct/profile-collection/profile=dfm-1-0-0-response-p-*_/response-profile-1-0:response-profile-pac/response-profile-capability/datatype]' 
    * @member {String} datatype
    */
    'datatype' = undefined;




}
