/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20051 model module.
* @module model/InlineResponse20051
* @version 1.0.1
*/
export default class InlineResponse20051 {
    /**
    * Constructs a new <code>InlineResponse20051</code>.
    * @alias module:model/InlineResponse20051
    * @class
    * @param operationClientInterface10operationalState {module:model/InlineResponse20051.OperationClientInterface10operationalStateEnum} 
    */

    constructor(operationClientInterface10operationalState) {
        
        
        this['operation-client-interface-1-0:operational-state'] = operationClientInterface10operationalState;
        
    }

    /**
    * Constructs a <code>InlineResponse20051</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20051} obj Optional instance to populate.
    * @return {module:model/InlineResponse20051} The populated <code>InlineResponse20051</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20051();
                        
            
            if (data.hasOwnProperty('operation-client-interface-1-0:operational-state')) {
                obj['operation-client-interface-1-0:operational-state'] = ApiClient.convertToType(data['operation-client-interface-1-0:operational-state'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/InlineResponse20051.OperationClientInterface10operationalStateEnum} operation-client-interface-1-0:operational-state
    */
    'operation-client-interface-1-0:operational-state' = undefined;



    /**
    * Allowed values for the <code>operation-client-interface-1-0:operational-state</code> property.
    * @enum {String}
    * @readonly
    */
    static OperationClientInterface10operationalStateEnum = {
        /**
         * value: "operation-client-interface-1-0:OPERATIONAL_STATE_TYPE_AVAILABLE"
         * @const
         */
        "AVAILABLE": "operation-client-interface-1-0:OPERATIONAL_STATE_TYPE_AVAILABLE",
        /**
         * value: "operation-client-interface-1-0:OPERATIONAL_STATE_TYPE_UNAVAILABLE"
         * @const
         */
        "UNAVAILABLE": "operation-client-interface-1-0:OPERATIONAL_STATE_TYPE_UNAVAILABLE",
        /**
         * value: "operation-client-interface-1-0:OPERATIONAL_STATE_TYPE_NOT_YET_DEFINED"
         * @const
         */
        "NOT_YET_DEFINED": "operation-client-interface-1-0:OPERATIONAL_STATE_TYPE_NOT_YET_DEFINED"    };

}
