/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20013Coremodel14controlconstruct from './InlineResponse20013Coremodel14controlconstruct';

/**
* The InlineResponse20013 model module.
* @module model/InlineResponse20013
* @version 1.0.1
*/
export default class InlineResponse20013 {
    /**
    * Constructs a new <code>InlineResponse20013</code>.
    * @alias module:model/InlineResponse20013
    * @class
    * @param coreModel14controlConstruct {module:model/InlineResponse20013Coremodel14controlconstruct} 
    */

    constructor(coreModel14controlConstruct) {
        
        
        this['core-model-1-4:control-construct'] = coreModel14controlConstruct;
        
    }

    /**
    * Constructs a <code>InlineResponse20013</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20013} obj Optional instance to populate.
    * @return {module:model/InlineResponse20013} The populated <code>InlineResponse20013</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20013();
                        
            
            if (data.hasOwnProperty('core-model-1-4:control-construct')) {
                obj['core-model-1-4:control-construct'] = InlineResponse20013Coremodel14controlconstruct.constructFromObject(data['core-model-1-4:control-construct']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/InlineResponse20013Coremodel14controlconstruct} core-model-1-4:control-construct
    */
    'core-model-1-4:control-construct' = undefined;




}
