/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20039 model module.
* @module model/InlineResponse20039
* @version 1.0.1
*/
export default class InlineResponse20039 {
    /**
    * Constructs a new <code>InlineResponse20039</code>.
    * @alias module:model/InlineResponse20039
    * @class
    * @param httpServerInterface10releaseNumber {String} 
    */

    constructor(httpServerInterface10releaseNumber) {
        
        
        this['http-server-interface-1-0:release-number'] = httpServerInterface10releaseNumber;
        
    }

    /**
    * Constructs a <code>InlineResponse20039</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20039} obj Optional instance to populate.
    * @return {module:model/InlineResponse20039} The populated <code>InlineResponse20039</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20039();
                        
            
            if (data.hasOwnProperty('http-server-interface-1-0:release-number')) {
                obj['http-server-interface-1-0:release-number'] = ApiClient.convertToType(data['http-server-interface-1-0:release-number'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} http-server-interface-1-0:release-number
    */
    'http-server-interface-1-0:release-number' = undefined;




}
