/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse2008 model module.
* @module model/InlineResponse2008
* @version 1.0.1
*/
export default class InlineResponse2008 {
    /**
    * Constructs a new <code>InlineResponse2008</code>.
    * @alias module:model/InlineResponse2008
    * @class
    * @param mountName {String} 
    * @param vendor {String} 
    * @param model {String} 
    * @param deviceConnectionStatus {module:model/InlineResponse2008.DeviceConnectionStatusEnum} 'The connection-status of the device (connected if, connected at the Controller; of disconnected of mounted at the Controller, but not in connected state) 
    * @param firmwareVersion {String} 'Current active firmware version of the device' 
    */

    constructor(mountName, vendor, model, deviceConnectionStatus, firmwareVersion) {
        
        
        this['mount-name'] = mountName;
        this['vendor'] = vendor;
        this['model'] = model;
        this['device-connection-status'] = deviceConnectionStatus;
        this['firmware-version'] = firmwareVersion;
        
    }

    /**
    * Constructs a <code>InlineResponse2008</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2008} obj Optional instance to populate.
    * @return {module:model/InlineResponse2008} The populated <code>InlineResponse2008</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2008();
                        
            
            if (data.hasOwnProperty('mount-name')) {
                obj['mount-name'] = ApiClient.convertToType(data['mount-name'], 'String');
            }
            if (data.hasOwnProperty('vendor')) {
                obj['vendor'] = ApiClient.convertToType(data['vendor'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('device-connection-status')) {
                obj['device-connection-status'] = ApiClient.convertToType(data['device-connection-status'], 'String');
            }
            if (data.hasOwnProperty('firmware-version')) {
                obj['firmware-version'] = ApiClient.convertToType(data['firmware-version'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} mount-name
    */
    'mount-name' = undefined;
    /**
    * @member {String} vendor
    */
    'vendor' = undefined;
    /**
    * @member {String} model
    */
    'model' = undefined;
    /**
    * 'The connection-status of the device (connected if, connected at the Controller; of disconnected of mounted at the Controller, but not in connected state) 
    * @member {module:model/InlineResponse2008.DeviceConnectionStatusEnum} device-connection-status
    */
    'device-connection-status' = undefined;
    /**
    * 'Current active firmware version of the device' 
    * @member {String} firmware-version
    */
    'firmware-version' = undefined;



    /**
    * Allowed values for the <code>device-connection-status</code> property.
    * @enum {String}
    * @readonly
    */
    static DeviceConnectionStatusEnum = {
        /**
         * value: "connected"
         * @const
         */
        "connected": "connected",
        /**
         * value: "disconnected"
         * @const
         */
        "disconnected": "disconnected"    };

}
