/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20035 model module.
* @module model/InlineResponse20035
* @version 1.0.1
*/
export default class InlineResponse20035 {
    /**
    * Constructs a new <code>InlineResponse20035</code>.
    * @alias module:model/InlineResponse20035
    * @class
    * @param operationServerInterface10operationName {String} 
    */

    constructor(operationServerInterface10operationName) {
        
        
        this['operation-server-interface-1-0:operation-name'] = operationServerInterface10operationName;
        
    }

    /**
    * Constructs a <code>InlineResponse20035</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20035} obj Optional instance to populate.
    * @return {module:model/InlineResponse20035} The populated <code>InlineResponse20035</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20035();
                        
            
            if (data.hasOwnProperty('operation-server-interface-1-0:operation-name')) {
                obj['operation-server-interface-1-0:operation-name'] = ApiClient.convertToType(data['operation-server-interface-1-0:operation-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} operation-server-interface-1-0:operation-name
    */
    'operation-server-interface-1-0:operation-name' = undefined;




}
