/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse2001 model module.
* @module model/InlineResponse2001
* @version 1.0.1
*/
export default class InlineResponse2001 {
    /**
    * Constructs a new <code>InlineResponse2001</code>.
    * @alias module:model/InlineResponse2001
    * @class
    * @param serverName {String} 'Name of the server' 
    * @param serverId {String} 'Server Id Details' 
    * @param destinationUrl {String} 'Destination SSH server location as url starting with sftp://{IP_Address}:{Port}/{Directory}' 
    * @param usernameAtFileServer {String} 'Username for SSH server' 
    * @param passwordAtFileServer {String} 'Encrypted Password for SSH server' 
    * @param sshKey {String} 'SSH Key of the server' 
    * @param retentionPeriod {Number} 'retention period' 
    */

    constructor(serverName, serverId, destinationUrl, usernameAtFileServer, passwordAtFileServer, sshKey, retentionPeriod) {
        
        
        this['server-name'] = serverName;
        this['server-id'] = serverId;
        this['destination-url'] = destinationUrl;
        this['username-at-file-server'] = usernameAtFileServer;
        this['password-at-file-server'] = passwordAtFileServer;
        this['ssh-key'] = sshKey;
        this['retention-period'] = retentionPeriod;
        
    }

    /**
    * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2001} obj Optional instance to populate.
    * @return {module:model/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001();
                        
            
            if (data.hasOwnProperty('server-name')) {
                obj['server-name'] = ApiClient.convertToType(data['server-name'], 'String');
            }
            if (data.hasOwnProperty('server-id')) {
                obj['server-id'] = ApiClient.convertToType(data['server-id'], 'String');
            }
            if (data.hasOwnProperty('destination-url')) {
                obj['destination-url'] = ApiClient.convertToType(data['destination-url'], 'String');
            }
            if (data.hasOwnProperty('username-at-file-server')) {
                obj['username-at-file-server'] = ApiClient.convertToType(data['username-at-file-server'], 'String');
            }
            if (data.hasOwnProperty('password-at-file-server')) {
                obj['password-at-file-server'] = ApiClient.convertToType(data['password-at-file-server'], 'String');
            }
            if (data.hasOwnProperty('ssh-key')) {
                obj['ssh-key'] = ApiClient.convertToType(data['ssh-key'], 'String');
            }
            if (data.hasOwnProperty('retention-period')) {
                obj['retention-period'] = ApiClient.convertToType(data['retention-period'], 'Number');
            }
        }
        return obj;
    }

    /**
    * 'Name of the server' 
    * @member {String} server-name
    */
    'server-name' = undefined;
    /**
    * 'Server Id Details' 
    * @member {String} server-id
    */
    'server-id' = undefined;
    /**
    * 'Destination SSH server location as url starting with sftp://{IP_Address}:{Port}/{Directory}' 
    * @member {String} destination-url
    */
    'destination-url' = undefined;
    /**
    * 'Username for SSH server' 
    * @member {String} username-at-file-server
    */
    'username-at-file-server' = undefined;
    /**
    * 'Encrypted Password for SSH server' 
    * @member {String} password-at-file-server
    */
    'password-at-file-server' = undefined;
    /**
    * 'SSH Key of the server' 
    * @member {String} ssh-key
    */
    'ssh-key' = undefined;
    /**
    * 'retention period' 
    * @member {Number} retention-period
    */
    'retention-period' = undefined;




}
