/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse2006 model module.
* @module model/InlineResponse2006
* @version 1.0.1
*/
export default class InlineResponse2006 {
    /**
    * Constructs a new <code>InlineResponse2006</code>.
    * @alias module:model/InlineResponse2006
    * @class
    * @param mountNameList {Array.<String>} 
    */

    constructor(mountNameList) {
        
        
        this['mount-name-list'] = mountNameList;
        
    }

    /**
    * Constructs a <code>InlineResponse2006</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2006} obj Optional instance to populate.
    * @return {module:model/InlineResponse2006} The populated <code>InlineResponse2006</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2006();
                        
            
            if (data.hasOwnProperty('mount-name-list')) {
                obj['mount-name-list'] = ApiClient.convertToType(data['mount-name-list'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} mount-name-list
    */
    'mount-name-list' = undefined;




}
