/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse2005 model module.
* @module model/InlineResponse2005
* @version 1.0.1
*/
export default class InlineResponse2005 {
    /**
    * Constructs a new <code>InlineResponse2005</code>.
    * @alias module:model/InlineResponse2005
    * @class
    * @param username {String} 
    * @param basicAuthRequestIsApproved {Boolean} 
    */

    constructor(username, basicAuthRequestIsApproved) {
        
        
        this['username'] = username;
        this['basic-auth-request-is-approved'] = basicAuthRequestIsApproved;
        
    }

    /**
    * Constructs a <code>InlineResponse2005</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2005} obj Optional instance to populate.
    * @return {module:model/InlineResponse2005} The populated <code>InlineResponse2005</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2005();
                        
            
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('basic-auth-request-is-approved')) {
                obj['basic-auth-request-is-approved'] = ApiClient.convertToType(data['basic-auth-request-is-approved'], 'Boolean');
            }
            if (data.hasOwnProperty('reason-of-objection')) {
                obj['reason-of-objection'] = ApiClient.convertToType(data['reason-of-objection'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} username
    */
    'username' = undefined;
    /**
    * @member {Boolean} basic-auth-request-is-approved
    */
    'basic-auth-request-is-approved' = undefined;
    /**
    * @member {String} reason-of-objection
    */
    'reason-of-objection' = undefined;




}
