/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20032 model module.
* @module model/InlineResponse20032
* @version 1.0.1
*/
export default class InlineResponse20032 {
    /**
    * Constructs a new <code>InlineResponse20032</code>.
    * @alias module:model/InlineResponse20032
    * @class
    * @param fileProfile10fileDescription {String} 
    */

    constructor(fileProfile10fileDescription) {
        
        
        this['file-profile-1-0:file-description'] = fileProfile10fileDescription;
        
    }

    /**
    * Constructs a <code>InlineResponse20032</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20032} obj Optional instance to populate.
    * @return {module:model/InlineResponse20032} The populated <code>InlineResponse20032</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20032();
                        
            
            if (data.hasOwnProperty('file-profile-1-0:file-description')) {
                obj['file-profile-1-0:file-description'] = ApiClient.convertToType(data['file-profile-1-0:file-description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} file-profile-1-0:file-description
    */
    'file-profile-1-0:file-description' = undefined;




}
