/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20048 model module.
* @module model/InlineResponse20048
* @version 1.0.1
*/
export default class InlineResponse20048 {
    /**
    * Constructs a new <code>InlineResponse20048</code>.
    * @alias module:model/InlineResponse20048
    * @class
    * @param tcpServerInterface10localPort {Number} 
    */

    constructor(tcpServerInterface10localPort) {
        
        
        this['tcp-server-interface-1-0:local-port'] = tcpServerInterface10localPort;
        
    }

    /**
    * Constructs a <code>InlineResponse20048</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20048} obj Optional instance to populate.
    * @return {module:model/InlineResponse20048} The populated <code>InlineResponse20048</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20048();
                        
            
            if (data.hasOwnProperty('tcp-server-interface-1-0:local-port')) {
                obj['tcp-server-interface-1-0:local-port'] = ApiClient.convertToType(data['tcp-server-interface-1-0:local-port'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} tcp-server-interface-1-0:local-port
    */
    'tcp-server-interface-1-0:local-port' = undefined;




}
