/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ForwardingDomainName from './ForwardingDomainName';
import InlineResponse20019Coremodel14controlconstructFcport from './InlineResponse20019Coremodel14controlconstructFcport';

/**
* The InlineResponse20019Coremodel14controlconstructForwardingconstruct model module.
* @module model/InlineResponse20019Coremodel14controlconstructForwardingconstruct
* @version 1.0.1
*/
export default class InlineResponse20019Coremodel14controlconstructForwardingconstruct {
    /**
    * Constructs a new <code>InlineResponse20019Coremodel14controlconstructForwardingconstruct</code>.
    * @alias module:model/InlineResponse20019Coremodel14controlconstructForwardingconstruct
    * @class
    * @param uuid {String} 
    * @param name {Array.<module:model/ForwardingDomainName>} 
    * @param fcPort {Array.<module:model/InlineResponse20019Coremodel14controlconstructFcport>} 
    */

    constructor(uuid, name, fcPort) {
        
        
        this['uuid'] = uuid;
        this['name'] = name;
        this['fc-port'] = fcPort;
        
    }

    /**
    * Constructs a <code>InlineResponse20019Coremodel14controlconstructForwardingconstruct</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20019Coremodel14controlconstructForwardingconstruct} obj Optional instance to populate.
    * @return {module:model/InlineResponse20019Coremodel14controlconstructForwardingconstruct} The populated <code>InlineResponse20019Coremodel14controlconstructForwardingconstruct</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20019Coremodel14controlconstructForwardingconstruct();
                        
            
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], [ForwardingDomainName]);
            }
            if (data.hasOwnProperty('fc-port')) {
                obj['fc-port'] = ApiClient.convertToType(data['fc-port'], [InlineResponse20019Coremodel14controlconstructFcport]);
            }
        }
        return obj;
    }

    /**
    * @member {String} uuid
    */
    'uuid' = undefined;
    /**
    * @member {Array.<module:model/ForwardingDomainName>} name
    */
    'name' = undefined;
    /**
    * @member {Array.<module:model/InlineResponse20019Coremodel14controlconstructFcport>} fc-port
    */
    'fc-port' = undefined;




}
