/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20053 model module.
* @module model/InlineResponse20053
* @version 1.0.1
*/
export default class InlineResponse20053 {
    /**
    * Constructs a new <code>InlineResponse20053</code>.
    * @alias module:model/InlineResponse20053
    * @class
    * @param operationClientInterface10detailedLoggingIsOn {Boolean} 
    */

    constructor(operationClientInterface10detailedLoggingIsOn) {
        
        
        this['operation-client-interface-1-0:detailed-logging-is-on'] = operationClientInterface10detailedLoggingIsOn;
        
    }

    /**
    * Constructs a <code>InlineResponse20053</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20053} obj Optional instance to populate.
    * @return {module:model/InlineResponse20053} The populated <code>InlineResponse20053</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20053();
                        
            
            if (data.hasOwnProperty('operation-client-interface-1-0:detailed-logging-is-on')) {
                obj['operation-client-interface-1-0:detailed-logging-is-on'] = ApiClient.convertToType(data['operation-client-interface-1-0:detailed-logging-is-on'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} operation-client-interface-1-0:detailed-logging-is-on
    */
    'operation-client-interface-1-0:detailed-logging-is-on' = undefined;




}
