/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20034 model module.
* @module model/InlineResponse20034
* @version 1.0.1
*/
export default class InlineResponse20034 {
    /**
    * Constructs a new <code>InlineResponse20034</code>.
    * @alias module:model/InlineResponse20034
    * @class
    * @param fileProfile10operation {module:model/InlineResponse20034.FileProfile10operationEnum} 
    */

    constructor(fileProfile10operation) {
        
        
        this['file-profile-1-0:operation'] = fileProfile10operation;
        
    }

    /**
    * Constructs a <code>InlineResponse20034</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20034} obj Optional instance to populate.
    * @return {module:model/InlineResponse20034} The populated <code>InlineResponse20034</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20034();
                        
            
            if (data.hasOwnProperty('file-profile-1-0:operation')) {
                obj['file-profile-1-0:operation'] = ApiClient.convertToType(data['file-profile-1-0:operation'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/InlineResponse20034.FileProfile10operationEnum} file-profile-1-0:operation
    */
    'file-profile-1-0:operation' = undefined;



    /**
    * Allowed values for the <code>file-profile-1-0:operation</code> property.
    * @enum {String}
    * @readonly
    */
    static FileProfile10operationEnum = {
        /**
         * value: "file-profile-1-0:OPERATION_TYPE_READ_ONLY"
         * @const
         */
        "READ_ONLY": "file-profile-1-0:OPERATION_TYPE_READ_ONLY",
        /**
         * value: "file-profile-1-0:OPERATION_TYPE_READ_WRITE"
         * @const
         */
        "READ_WRITE": "file-profile-1-0:OPERATION_TYPE_READ_WRITE",
        /**
         * value: "file-profile-1-0:OPERATION_TYPE_OFF"
         * @const
         */
        "OFF": "file-profile-1-0:OPERATION_TYPE_OFF",
        /**
         * value: "file-profile-1-0:OPERATION_TYPE_NOT_YET_DEFINED"
         * @const
         */
        "NOT_YET_DEFINED": "file-profile-1-0:OPERATION_TYPE_NOT_YET_DEFINED"    };

}
