/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20027Responseprofile10fieldname model module.
* @module model/InlineResponse20027Responseprofile10fieldname
* @version 1.0.1
*/
export default class InlineResponse20027Responseprofile10fieldname {
    /**
    * Constructs a new <code>InlineResponse20027Responseprofile10fieldname</code>.
    * @alias module:model/InlineResponse20027Responseprofile10fieldname
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>InlineResponse20027Responseprofile10fieldname</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20027Responseprofile10fieldname} obj Optional instance to populate.
    * @return {module:model/InlineResponse20027Responseprofile10fieldname} The populated <code>InlineResponse20027Responseprofile10fieldname</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20027Responseprofile10fieldname();
                        
            
            if (data.hasOwnProperty('static-field-name')) {
                obj['static-field-name'] = ApiClient.convertToType(data['static-field-name'], 'String');
            }
            if (data.hasOwnProperty('field-name-reference')) {
                obj['field-name-reference'] = ApiClient.convertToType(data['field-name-reference'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} static-field-name
    */
    'static-field-name' = undefined;
    /**
    * @member {String} field-name-reference
    */
    'field-name-reference' = undefined;




}
