/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20052 model module.
* @module model/InlineResponse20052
* @version 1.0.1
*/
export default class InlineResponse20052 {
    /**
    * Constructs a new <code>InlineResponse20052</code>.
    * @alias module:model/InlineResponse20052
    * @class
    * @param operationClientInterface10lifeCycleState {module:model/InlineResponse20052.OperationClientInterface10lifeCycleStateEnum} 
    */

    constructor(operationClientInterface10lifeCycleState) {
        
        
        this['operation-client-interface-1-0:life-cycle-state'] = operationClientInterface10lifeCycleState;
        
    }

    /**
    * Constructs a <code>InlineResponse20052</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20052} obj Optional instance to populate.
    * @return {module:model/InlineResponse20052} The populated <code>InlineResponse20052</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20052();
                        
            
            if (data.hasOwnProperty('operation-client-interface-1-0:life-cycle-state')) {
                obj['operation-client-interface-1-0:life-cycle-state'] = ApiClient.convertToType(data['operation-client-interface-1-0:life-cycle-state'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/InlineResponse20052.OperationClientInterface10lifeCycleStateEnum} operation-client-interface-1-0:life-cycle-state
    */
    'operation-client-interface-1-0:life-cycle-state' = undefined;



    /**
    * Allowed values for the <code>operation-client-interface-1-0:life-cycle-state</code> property.
    * @enum {String}
    * @readonly
    */
    static OperationClientInterface10lifeCycleStateEnum = {
        /**
         * value: "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_EXPERIMENTAL"
         * @const
         */
        "EXPERIMENTAL": "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_EXPERIMENTAL",
        /**
         * value: "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OPERATIONAL"
         * @const
         */
        "OPERATIONAL": "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OPERATIONAL",
        /**
         * value: "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_DEPRECATED"
         * @const
         */
        "DEPRECATED": "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_DEPRECATED",
        /**
         * value: "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OBSOLETE"
         * @const
         */
        "OBSOLETE": "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OBSOLETE",
        /**
         * value: "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_UNKNOWN"
         * @const
         */
        "UNKNOWN": "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_UNKNOWN",
        /**
         * value: "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_NOT_YET_DEFINED"
         * @const
         */
        "NOT_YET_DEFINED": "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_NOT_YET_DEFINED"    };

}
