/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse202 model module.
* @module model/InlineResponse202
* @version 1.0.1
*/
export default class InlineResponse202 {
    /**
    * Constructs a new <code>InlineResponse202</code>.
    * @alias module:model/InlineResponse202
    * @class
    * @param mountName {String} 'mount name' 
    * @param jobId {String} 'Auto generated Job Id for the scheduled job' 
    * @param deviceBackupStatus {module:model/InlineResponse202.DeviceBackupStatusEnum} 
    */

    constructor(mountName, jobId, deviceBackupStatus) {
        
        
        this['mount-name'] = mountName;
        this['job-id'] = jobId;
        this['device-backup-status'] = deviceBackupStatus;
        
    }

    /**
    * Constructs a <code>InlineResponse202</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse202} obj Optional instance to populate.
    * @return {module:model/InlineResponse202} The populated <code>InlineResponse202</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse202();
                        
            
            if (data.hasOwnProperty('mount-name')) {
                obj['mount-name'] = ApiClient.convertToType(data['mount-name'], 'String');
            }
            if (data.hasOwnProperty('job-id')) {
                obj['job-id'] = ApiClient.convertToType(data['job-id'], 'String');
            }
            if (data.hasOwnProperty('device-backup-status')) {
                obj['device-backup-status'] = ApiClient.convertToType(data['device-backup-status'], 'String');
            }
            if (data.hasOwnProperty('device-connection-status')) {
                obj['device-connection-status'] = ApiClient.convertToType(data['device-connection-status'], 'String');
            }
            if (data.hasOwnProperty('retry-eligible')) {
                obj['retry-eligible'] = ApiClient.convertToType(data['retry-eligible'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * 'mount name' 
    * @member {String} mount-name
    */
    'mount-name' = undefined;
    /**
    * 'Auto generated Job Id for the scheduled job' 
    * @member {String} job-id
    */
    'job-id' = undefined;
    /**
    * @member {module:model/InlineResponse202.DeviceBackupStatusEnum} device-backup-status
    */
    'device-backup-status' = undefined;
    /**
    * 'The connection-status of the device (connected if, connected at the Controller; of disconnected of mounted at the Controller, but not in connected state) 
    * @member {module:model/InlineResponse202.DeviceConnectionStatusEnum} device-connection-status
    */
    'device-connection-status' = undefined;
    /**
    * Is it eligible for retry
    * @member {Boolean} retry-eligible
    */
    'retry-eligible' = undefined;



    /**
    * Allowed values for the <code>device-backup-status</code> property.
    * @enum {String}
    * @readonly
    */
    static DeviceBackupStatusEnum = {
        /**
         * value: "ONGOING"
         * @const
         */
        "ONGOING": "ONGOING"    };
    /**
    * Allowed values for the <code>device-connection-status</code> property.
    * @enum {String}
    * @readonly
    */
    static DeviceConnectionStatusEnum = {
        /**
         * value: "connected"
         * @const
         */
        "connected": "connected",
        /**
         * value: "disconnected"
         * @const
         */
        "disconnected": "disconnected"    };

}
