/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20017 model module.
* @module model/InlineResponse20017
* @version 1.0.1
*/
export default class InlineResponse20017 {
    /**
    * Constructs a new <code>InlineResponse20017</code>.
    * @alias module:model/InlineResponse20017
    * @class
    * @param applicationName {String} 'Own application name from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/application-name]' 
    * @param releaseNumber {String} 'Own release number from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/release-number]' 
    * @param applicationPurpose {String} 'Own application purpose from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/application-purpose]' 
    * @param dataUpdatePeriod {module:model/InlineResponse20017.DataUpdatePeriodEnum} from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/data-update-period]
    * @param ownerName {String} from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/owner-name]
    * @param ownerEmailAddress {String} from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/owner-email-address]
    */

    constructor(applicationName, releaseNumber, applicationPurpose, dataUpdatePeriod, ownerName, ownerEmailAddress) {
        
        
        this['application-name'] = applicationName;
        this['release-number'] = releaseNumber;
        this['application-purpose'] = applicationPurpose;
        this['data-update-period'] = dataUpdatePeriod;
        this['owner-name'] = ownerName;
        this['owner-email-address'] = ownerEmailAddress;
        
    }

    /**
    * Constructs a <code>InlineResponse20017</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20017} obj Optional instance to populate.
    * @return {module:model/InlineResponse20017} The populated <code>InlineResponse20017</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20017();
                        
            
            if (data.hasOwnProperty('application-name')) {
                obj['application-name'] = ApiClient.convertToType(data['application-name'], 'String');
            }
            if (data.hasOwnProperty('release-number')) {
                obj['release-number'] = ApiClient.convertToType(data['release-number'], 'String');
            }
            if (data.hasOwnProperty('application-purpose')) {
                obj['application-purpose'] = ApiClient.convertToType(data['application-purpose'], 'String');
            }
            if (data.hasOwnProperty('data-update-period')) {
                obj['data-update-period'] = ApiClient.convertToType(data['data-update-period'], 'String');
            }
            if (data.hasOwnProperty('owner-name')) {
                obj['owner-name'] = ApiClient.convertToType(data['owner-name'], 'String');
            }
            if (data.hasOwnProperty('owner-email-address')) {
                obj['owner-email-address'] = ApiClient.convertToType(data['owner-email-address'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'Own application name from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/application-name]' 
    * @member {String} application-name
    */
    'application-name' = undefined;
    /**
    * 'Own release number from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/release-number]' 
    * @member {String} release-number
    */
    'release-number' = undefined;
    /**
    * 'Own application purpose from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/application-purpose]' 
    * @member {String} application-purpose
    */
    'application-purpose' = undefined;
    /**
    * from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/data-update-period]
    * @member {module:model/InlineResponse20017.DataUpdatePeriodEnum} data-update-period
    */
    'data-update-period' = undefined;
    /**
    * from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/owner-name]
    * @member {String} owner-name
    */
    'owner-name' = undefined;
    /**
    * from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/owner-email-address]
    * @member {String} owner-email-address
    */
    'owner-email-address' = undefined;



    /**
    * Allowed values for the <code>data-update-period</code> property.
    * @enum {String}
    * @readonly
    */
    static DataUpdatePeriodEnum = {
        /**
         * value: "real-time"
         * @const
         */
        "real-time": "real-time",
        /**
         * value: "1h-period"
         * @const
         */
        "1h-period": "1h-period",
        /**
         * value: "24h-period"
         * @const
         */
        "24h-period": "24h-period",
        /**
         * value: "manual"
         * @const
         */
        "manual": "manual"    };

}
