/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20043 model module.
* @module model/InlineResponse20043
* @version 1.0.1
*/
export default class InlineResponse20043 {
    /**
    * Constructs a new <code>InlineResponse20043</code>.
    * @alias module:model/InlineResponse20043
    * @class
    * @param httpServerInterface10ownerEmailAddress {String} 
    */

    constructor(httpServerInterface10ownerEmailAddress) {
        
        
        this['http-server-interface-1-0:owner-email-address'] = httpServerInterface10ownerEmailAddress;
        
    }

    /**
    * Constructs a <code>InlineResponse20043</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20043} obj Optional instance to populate.
    * @return {module:model/InlineResponse20043} The populated <code>InlineResponse20043</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20043();
                        
            
            if (data.hasOwnProperty('http-server-interface-1-0:owner-email-address')) {
                obj['http-server-interface-1-0:owner-email-address'] = ApiClient.convertToType(data['http-server-interface-1-0:owner-email-address'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} http-server-interface-1-0:owner-email-address
    */
    'http-server-interface-1-0:owner-email-address' = undefined;




}
