/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelObject from './ModelObject';

/**
* The InlineResponse20020 model module.
* @module model/InlineResponse20020
* @version 1.0.1
*/
export default class InlineResponse20020 {
    /**
    * Constructs a new <code>InlineResponse20020</code>.
    * @alias module:model/InlineResponse20020
    * @class
    * @param coreModel14profile {module:model/ModelObject} 
    */

    constructor(coreModel14profile) {
        
        
        this['core-model-1-4:profile'] = coreModel14profile;
        
    }

    /**
    * Constructs a <code>InlineResponse20020</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20020} obj Optional instance to populate.
    * @return {module:model/InlineResponse20020} The populated <code>InlineResponse20020</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20020();
                        
            
            if (data.hasOwnProperty('core-model-1-4:profile')) {
                obj['core-model-1-4:profile'] = ApiClient.convertToType(data['core-model-1-4:profile'], ModelObject);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ModelObject} core-model-1-4:profile
    */
    'core-model-1-4:profile' = undefined;




}
