/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20054 model module.
* @module model/InlineResponse20054
* @version 1.0.1
*/
export default class InlineResponse20054 {
    /**
    * Constructs a new <code>InlineResponse20054</code>.
    * @alias module:model/InlineResponse20054
    * @class
    * @param httpClientInterface10applicationName {String} 
    */

    constructor(httpClientInterface10applicationName) {
        
        
        this['http-client-interface-1-0:application-name'] = httpClientInterface10applicationName;
        
    }

    /**
    * Constructs a <code>InlineResponse20054</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20054} obj Optional instance to populate.
    * @return {module:model/InlineResponse20054} The populated <code>InlineResponse20054</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20054();
                        
            
            if (data.hasOwnProperty('http-client-interface-1-0:application-name')) {
                obj['http-client-interface-1-0:application-name'] = ApiClient.convertToType(data['http-client-interface-1-0:application-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} http-client-interface-1-0:application-name
    */
    'http-client-interface-1-0:application-name' = undefined;




}
