/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20025 model module.
* @module model/InlineResponse20025
* @version 1.0.1
*/
export default class InlineResponse20025 {
    /**
    * Constructs a new <code>InlineResponse20025</code>.
    * @alias module:model/InlineResponse20025
    * @class
    * @param actionProfile10consequentOperationReference {String} 
    */

    constructor(actionProfile10consequentOperationReference) {
        
        
        this['action-profile-1-0:consequent-operation-reference'] = actionProfile10consequentOperationReference;
        
    }

    /**
    * Constructs a <code>InlineResponse20025</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20025} obj Optional instance to populate.
    * @return {module:model/InlineResponse20025} The populated <code>InlineResponse20025</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20025();
                        
            
            if (data.hasOwnProperty('action-profile-1-0:consequent-operation-reference')) {
                obj['action-profile-1-0:consequent-operation-reference'] = ApiClient.convertToType(data['action-profile-1-0:consequent-operation-reference'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} action-profile-1-0:consequent-operation-reference
    */
    'action-profile-1-0:consequent-operation-reference' = undefined;




}
