/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse2009Latestbackupsmetadataofdevice model module.
* @module model/InlineResponse2009Latestbackupsmetadataofdevice
* @version 1.0.1
*/
export default class InlineResponse2009Latestbackupsmetadataofdevice {
    /**
    * Constructs a new <code>InlineResponse2009Latestbackupsmetadataofdevice</code>.
    * @alias module:model/InlineResponse2009Latestbackupsmetadataofdevice
    * @class
    * @param mountName {String} 'mount name' 
    * @param deviceBackupStatus {module:model/InlineResponse2009Latestbackupsmetadataofdevice.DeviceBackupStatusEnum} 
    * @param startTime {Date} Start time of the backup
    * @param backupJobId {String} backup job id
    * @param backupTime {Date} Backup time for completed backups, only present when device-backup-status is provided in the request
    */

    constructor(mountName, deviceBackupStatus, startTime, backupJobId) {
        
        
        this['mount-name'] = mountName;
        this['device-backup-status'] = deviceBackupStatus;
        this['start-time'] = startTime;
        this['backup-job-id'] = backupJobId;
        
    }

    /**
    * Constructs a <code>InlineResponse2009Latestbackupsmetadataofdevice</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2009Latestbackupsmetadataofdevice} obj Optional instance to populate.
    * @return {module:model/InlineResponse2009Latestbackupsmetadataofdevice} The populated <code>InlineResponse2009Latestbackupsmetadataofdevice</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2009Latestbackupsmetadataofdevice();
                        
            
            if (data.hasOwnProperty('mount-name')) {
                obj['mount-name'] = ApiClient.convertToType(data['mount-name'], 'String');
            }
            if (data.hasOwnProperty('device-backup-status')) {
                obj['device-backup-status'] = ApiClient.convertToType(data['device-backup-status'], 'String');
            }
            if (data.hasOwnProperty('firmware-version')) {
                obj['firmware-version'] = ApiClient.convertToType(data['firmware-version'], 'String');
            }
            if (data.hasOwnProperty('backup-server-name')) {
                obj['backup-server-name'] = ApiClient.convertToType(data['backup-server-name'], 'String');
            }
            if(data.hasOwnProperty('backup-file-stored-server-name')){
                obj['backup-file-stored-server-name'] = ApiClient.convertToType(data['backup-file-stored-server-name'], 'String');
            }
            if(data.hasOwnProperty('backup-file-name')){
                obj['backup-file-name'] = ApiClient.convertToType(data['backup-file-name'], 'String');
            }
            if (data.hasOwnProperty('start-time')) {
                obj['start-time'] = ApiClient.convertToType(data['start-time'], 'Date');
            }
            if (data.hasOwnProperty('end-time')) {
                obj['end-time'] = ApiClient.convertToType(data['end-time'], 'Date');
            }
            if (data.hasOwnProperty('backup-time')) {
                obj['backup-time'] = ApiClient.convertToType(data['backup-time'], 'Date');
            }
            if (data.hasOwnProperty('error-message')) {
                obj['error-message'] = ApiClient.convertToType(data['error-message'], 'String');
            }
            if (data.hasOwnProperty('backup-file-stored-path')) {
                obj['backup-file-stored-path'] = ApiClient.convertToType(data['backup-file-stored-path'], 'String');
            }
            if (data.hasOwnProperty('backup-job-id')) {
                obj['backup-job-id'] = ApiClient.convertToType(data['backup-job-id'], 'String');
            }
            if (data.hasOwnProperty('vendor')) {
                obj['vendor'] = ApiClient.convertToType(data['vendor'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'mount name' 
    * @member {String} mount-name
    */
    'mount-name' = undefined;
    /**
    * @member {module:model/InlineResponse2009Latestbackupsmetadataofdevice.DeviceBackupStatusEnum} device-backup-status
    */
    'device-backup-status' = undefined;
    /**
    * 'Current active firmware version of the device' 
    * @member {String} firmware-version
    */
    'firmware-version' = undefined;
    /**
    * 'Name of the server where the backup file shall be stored' 
    * @member {String} backup-server-name
    */
    'backup-server-name' = undefined;
    
    /**
     * 'Backup File Name
     * @member {String} backup-file-name
     */
    'backup-file-name' = undefined

    /**
     * 'Name of the Server where the backup file shall be stored'
     * @member {String} backup-file-stored-server-name
     */
    'backup-file-stored-server-name' = undefined;
    /**
    * Start time of the backup
    * @member {Date} start-time
    */
    'start-time' = undefined;
    /**
    * End time of the backup
    * @member {Date} end-time
    */
    'end-time' = undefined;
    /**
    * Backup time for completed backups, only present when device-backup-status is provided in the request
    * @member {Date} backup-time
    */
    'backup-time' = undefined;
    /**
    * error message provided if status is failed
    * @member {String} error-message
    */
    'error-message' = undefined;
    /**
    * Path where backup file is stored if status is completed
    * @member {String} backup-file-stored-path
    */
    'backup-file-stored-path' = undefined;
    /**
    * backup job id
    * @member {String} backup-job-id
    */
    'backup-job-id' = undefined;
    /**
    * vendor of device
    * @member {String} vendor
    */
    'vendor' = undefined;
    /**
    * model of device
    * @member {String} model
    */
    'model' = undefined;



    /**
    * Allowed values for the <code>device-backup-status</code> property.
    * @enum {String}
    * @readonly
    */
    static DeviceBackupStatusEnum = {
        /**
         * value: "IDLE"
         * @const
         */
        "IDLE": "IDLE",
        /**
         * value: "ONGOING"
         * @const
         */
        "ONGOING": "ONGOING",
        /**
         * value: "COMPLETED"
         * @const
         */
        "COMPLETED": "COMPLETED",
        /**
         * value: "FAILED"
         * @const
         */
        "FAILED": "FAILED"    };

}
