/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse2021 model module.
* @module model/InlineResponse2021
* @version 1.0.1
*/
export default class InlineResponse2021 {
    /**
    * Constructs a new <code>InlineResponse2021</code>.
    * @alias module:model/InlineResponse2021
    * @class
    * @param jobId {String} 'Auto generated Job Id for the scheduled job' 
    * @param status {module:model/InlineResponse2021.StatusEnum} 
    */

    constructor(jobId, status) {
        
        
        this['job-id'] = jobId;
        this['status'] = status;
        
    }

    /**
    * Constructs a <code>InlineResponse2021</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2021} obj Optional instance to populate.
    * @return {module:model/InlineResponse2021} The populated <code>InlineResponse2021</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2021();
                        
            
            if (data.hasOwnProperty('job-id')) {
                obj['job-id'] = ApiClient.convertToType(data['job-id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('aborted-by-user')) {
                obj['aborted-by-user'] = ApiClient.convertToType(data['aborted-by-user'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'Auto generated Job Id for the scheduled job' 
    * @member {String} job-id
    */
    'job-id' = undefined;
    /**
    * @member {module:model/InlineResponse2021.StatusEnum} status
    */
    'status' = undefined;
    /**
    * @member {String} aborted-by-user
    */
    'aborted-by-user' = undefined;



    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
        /**
         * value: "ABORTED"
         * @const
         */
        "ABORTED": "ABORTED"    };

}
