/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2004Devicebackupmetadata from './InlineResponse2004Devicebackupmetadata';

/**
* The InlineResponse2004 model module.
* @module model/InlineResponse2004
* @version 1.0.1
*/
export default class InlineResponse2004 {
    /**
    * Constructs a new <code>InlineResponse2004</code>.
    * @alias module:model/InlineResponse2004
    * @class
    * @param page {Number} 
    * @param size {Number} 
    * @param totalRecords {Number} 
    * @param deviceBackupMetadata {Array.<module:model/InlineResponse2004Devicebackupmetadata>} 
    */

    constructor(page, size, totalRecords, deviceBackupMetadata) {
        
        
        this['page'] = page;
        this['size'] = size;
        this['total-records'] = totalRecords;
        this['device-backup-metadata'] = deviceBackupMetadata;
        
    }

    /**
    * Constructs a <code>InlineResponse2004</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2004} obj Optional instance to populate.
    * @return {module:model/InlineResponse2004} The populated <code>InlineResponse2004</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2004();
                        
            
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('total-records')) {
                obj['total-records'] = ApiClient.convertToType(data['total-records'], 'Number');
            }
            if (data.hasOwnProperty('device-backup-metadata')) {
                obj['device-backup-metadata'] = ApiClient.convertToType(data['device-backup-metadata'], [InlineResponse2004Devicebackupmetadata]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} page
    */
    'page' = undefined;
    /**
    * @member {Number} size
    */
    'size' = undefined;
    /**
    * @member {Number} total-records
    */
    'total-records' = undefined;
    /**
    * @member {Array.<module:model/InlineResponse2004Devicebackupmetadata>} device-backup-metadata
    */
    'device-backup-metadata' = undefined;




}
