/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20049 model module.
* @module model/InlineResponse20049
* @version 1.0.1
*/
export default class InlineResponse20049 {
    /**
    * Constructs a new <code>InlineResponse20049</code>.
    * @alias module:model/InlineResponse20049
    * @class
    * @param operationClientInterface10operationName {String} 
    */

    constructor(operationClientInterface10operationName) {
        
        
        this['operation-client-interface-1-0:operation-name'] = operationClientInterface10operationName;
        
    }

    /**
    * Constructs a <code>InlineResponse20049</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20049} obj Optional instance to populate.
    * @return {module:model/InlineResponse20049} The populated <code>InlineResponse20049</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20049();
                        
            
            if (data.hasOwnProperty('operation-client-interface-1-0:operation-name')) {
                obj['operation-client-interface-1-0:operation-name'] = ApiClient.convertToType(data['operation-client-interface-1-0:operation-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} operation-client-interface-1-0:operation-name
    */
    'operation-client-interface-1-0:operation-name' = undefined;




}
