/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20045 model module.
* @module model/InlineResponse20045
* @version 1.0.1
*/
export default class InlineResponse20045 {
    /**
    * Constructs a new <code>InlineResponse20045</code>.
    * @alias module:model/InlineResponse20045
    * @class
    * @param tcpServerInterface10description {String} 
    */

    constructor(tcpServerInterface10description) {
        
        
        this['tcp-server-interface-1-0:description'] = tcpServerInterface10description;
        
    }

    /**
    * Constructs a <code>InlineResponse20045</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20045} obj Optional instance to populate.
    * @return {module:model/InlineResponse20045} The populated <code>InlineResponse20045</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20045();
                        
            
            if (data.hasOwnProperty('tcp-server-interface-1-0:description')) {
                obj['tcp-server-interface-1-0:description'] = ApiClient.convertToType(data['tcp-server-interface-1-0:description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} tcp-server-interface-1-0:description
    */
    'tcp-server-interface-1-0:description' = undefined;




}
