/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse2004Devicebackupmetadata model module.
* @module model/InlineResponse2004Devicebackupmetadata
* @version 1.0.1
*/
export default class InlineResponse2004Devicebackupmetadata {
    /**
    * Constructs a new <code>InlineResponse2004Devicebackupmetadata</code>.
    * @alias module:model/InlineResponse2004Devicebackupmetadata
    * @class
    * @param mountName {String} 'mount name' 
    * @param deviceBackupStatus {module:model/InlineResponse2004Devicebackupmetadata.DeviceBackupStatusEnum} 
    * @param startTime {Date} Start time of the backup
    * @param deviceConnectionStatus {module:model/InlineResponse2004Devicebackupmetadata.DeviceConnectionStatusEnum} 'The connection-status of the device (connected if, connected at the Controller; of disconnected of mounted at the Controller, but not in connected state) 
    */

    constructor(mountName, deviceBackupStatus, startTime, deviceConnectionStatus) {
        
        
        this['mount-name'] = mountName;
        this['device-backup-status'] = deviceBackupStatus;
        this['start-time'] = startTime;
        this['device-connection-status'] = deviceConnectionStatus;
        
    }

    /**
    * Constructs a <code>InlineResponse2004Devicebackupmetadata</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2004Devicebackupmetadata} obj Optional instance to populate.
    * @return {module:model/InlineResponse2004Devicebackupmetadata} The populated <code>InlineResponse2004Devicebackupmetadata</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2004Devicebackupmetadata();
                        
            
            if (data.hasOwnProperty('mount-name')) {
                obj['mount-name'] = ApiClient.convertToType(data['mount-name'], 'String');
            }
            if (data.hasOwnProperty('vendor')) {
                obj['vendor'] = ApiClient.convertToType(data['vendor'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('firmware-version')) {
                obj['firmware-version'] = ApiClient.convertToType(data['firmware-version'], 'String');
            }
            if (data.hasOwnProperty('device-backup-status')) {
                obj['device-backup-status'] = ApiClient.convertToType(data['device-backup-status'], 'String');
            }
            if (data.hasOwnProperty('retry-eligible')) {
                obj['retry-eligible'] = ApiClient.convertToType(data['retry-eligible'], 'Boolean');
            }
            if (data.hasOwnProperty('start-time')) {
                obj['start-time'] = ApiClient.convertToType(data['start-time'], 'Date');
            }
            if (data.hasOwnProperty('end-time')) {
                obj['end-time'] = ApiClient.convertToType(data['end-time'], 'Date');
            }
            if (data.hasOwnProperty('error-message')) {
                obj['error-message'] = ApiClient.convertToType(data['error-message'], 'String');
            }
            if (data.hasOwnProperty('backup-file-stored-path')) {
                obj['backup-file-stored-path'] = ApiClient.convertToType(data['backup-file-stored-path'], 'String');
            }
            if (data.hasOwnProperty('backup-file-name')) {
                obj['backup-file-name'] = ApiClient.convertToType(data['backup-file-name'], 'String');
            }
            if (data.hasOwnProperty('device-connection-status')) {
                obj['device-connection-status'] = ApiClient.convertToType(data['device-connection-status'], 'String');
            }
            if (data.hasOwnProperty('job-id')) {
                obj['job-id'] = ApiClient.convertToType(data['job-id'], 'String');
            }
            if (data.hasOwnProperty('schedule-id')) {
                obj['schedule-id'] = ApiClient.convertToType(data['schedule-id'], 'String');
            }
            if (data.hasOwnProperty('retry-attempt')) {
                obj['retry-attempt'] = ApiClient.convertToType(data['retry-attempt'], 'Number');
            }
            if (data.hasOwnProperty('backup-file-stored-server-name')) {
                obj['backup-file-stored-server-name'] = ApiClient.convertToType(data['backup-file-stored-server-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'mount name' 
    * @member {String} mount-name
    */
    'mount-name' = undefined;
    /**
    * Name of the vendor
    * @member {String} vendor
    */
    'vendor' = undefined;
    /**
    * Model of the device
    * @member {String} model
    */
    'model' = undefined;
    /**
    * 'Current active firmware version of the device' 
    * @member {String} firmware-version
    */
    'firmware-version' = undefined;
    /**
    * @member {module:model/InlineResponse2004Devicebackupmetadata.DeviceBackupStatusEnum} device-backup-status
    */
    'device-backup-status' = undefined;
    /**
    * Is it eligible for retry
    * @member {Boolean} retry-eligible
    */
    'retry-eligible' = undefined;
    /**
    * Start time of the backup
    * @member {Date} start-time
    */
    'start-time' = undefined;
    /**
    * End time of the backup
    * @member {Date} end-time
    */
    'end-time' = undefined;
    /**
    * error message provided if status is failed
    * @member {String} error-message
    */
    'error-message' = undefined;
    /**
    * Path where backup file is stored if status is completed
    * @member {String} backup-file-stored-path
    */
    'backup-file-stored-path' = undefined;
    /**
    * File name of the backup
    * @member {String} backup-file-name
    */
    'backup-file-name' = undefined;
    /**
    * 'The connection-status of the device (connected if, connected at the Controller; of disconnected of mounted at the Controller, but not in connected state) 
    * @member {module:model/InlineResponse2004Devicebackupmetadata.DeviceConnectionStatusEnum} device-connection-status
    */
    'device-connection-status' = undefined;
    /**
    * Job ID
    * @member {String} job-id
    */
    'job-id' = undefined;
    /**
    * Schedule ID
    * @member {String} schedule-id
    */
    'schedule-id' = undefined;
    /**
    * Number of retry attempts
    * @member {Number} retry-attempt
    */
    'retry-attempt' = undefined;
    /**
    * Server name where backup file is stored
    * @member {String} backup-file-stored-server-name
    */
    'backup-file-stored-server-name' = undefined;



    /**
    * Allowed values for the <code>device-backup-status</code> property.
    * @enum {String}
    * @readonly
    */
    static DeviceBackupStatusEnum = {
        /**
         * value: "IDLE"
         * @const
         */
        "IDLE": "IDLE",
        /**
         * value: "ONGOING"
         * @const
         */
        "ONGOING": "ONGOING",
        /**
         * value: "COMPLETED"
         * @const
         */
        "COMPLETED": "COMPLETED",
        /**
         * value: "FAILED"
         * @const
         */
        "FAILED": "FAILED"    };
    /**
    * Allowed values for the <code>device-connection-status</code> property.
    * @enum {String}
    * @readonly
    */
    static DeviceConnectionStatusEnum = {
        /**
         * value: "connected"
         * @const
         */
        "connected": "connected",
        /**
         * value: "disconnected"
         * @const
         */
        "disconnected": "disconnected"    };

}
