/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20019Coremodel14controlconstructFcport model module.
* @module model/InlineResponse20019Coremodel14controlconstructFcport
* @version 1.0.1
*/
export default class InlineResponse20019Coremodel14controlconstructFcport {
    /**
    * Constructs a new <code>InlineResponse20019Coremodel14controlconstructFcport</code>.
    * @alias module:model/InlineResponse20019Coremodel14controlconstructFcport
    * @class
    * @param localId {String} 
    * @param portDirection {module:model/InlineResponse20019Coremodel14controlconstructFcport.PortDirectionEnum} 
    * @param logicalTerminationPoint {String} 
    */

    constructor(localId, portDirection, logicalTerminationPoint) {
        
        
        this['local-id'] = localId;
        this['port-direction'] = portDirection;
        this['logical-termination-point'] = logicalTerminationPoint;
        
    }

    /**
    * Constructs a <code>InlineResponse20019Coremodel14controlconstructFcport</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20019Coremodel14controlconstructFcport} obj Optional instance to populate.
    * @return {module:model/InlineResponse20019Coremodel14controlconstructFcport} The populated <code>InlineResponse20019Coremodel14controlconstructFcport</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20019Coremodel14controlconstructFcport();
                        
            
            if (data.hasOwnProperty('local-id')) {
                obj['local-id'] = ApiClient.convertToType(data['local-id'], 'String');
            }
            if (data.hasOwnProperty('port-direction')) {
                obj['port-direction'] = ApiClient.convertToType(data['port-direction'], 'String');
            }
            if (data.hasOwnProperty('logical-termination-point')) {
                obj['logical-termination-point'] = ApiClient.convertToType(data['logical-termination-point'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} local-id
    */
    'local-id' = undefined;
    /**
    * @member {module:model/InlineResponse20019Coremodel14controlconstructFcport.PortDirectionEnum} port-direction
    */
    'port-direction' = undefined;
    /**
    * @member {String} logical-termination-point
    */
    'logical-termination-point' = undefined;



    /**
    * Allowed values for the <code>port-direction</code> property.
    * @enum {String}
    * @readonly
    */
    static PortDirectionEnum = {
        /**
         * value: "core-model-1-4:PORT_DIRECTION_TYPE_MANAGEMENT"
         * @const
         */
        "MANAGEMENT": "core-model-1-4:PORT_DIRECTION_TYPE_MANAGEMENT",
        /**
         * value: "core-model-1-4:PORT_DIRECTION_TYPE_INPUT"
         * @const
         */
        "INPUT": "core-model-1-4:PORT_DIRECTION_TYPE_INPUT",
        /**
         * value: "core-model-1-4:PORT_DIRECTION_TYPE_OUTPUT"
         * @const
         */
        "OUTPUT": "core-model-1-4:PORT_DIRECTION_TYPE_OUTPUT"    };

}
