/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20016 model module.
* @module model/InlineResponse20016
* @version 1.0.1
*/
export default class InlineResponse20016 {
    /**
    * Constructs a new <code>InlineResponse20016</code>.
    * @alias module:model/InlineResponse20016
    * @class
    * @param bequeathYourDataAndDieOperation {String} 'Operation for starting the handover process on the already existing application from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-s-im-000/layer-protocol=0/operation-server-interface-1-0:operation-server-interface-pac/operation-server-interface-capability/operation-name]' 
    * @param dataTransferOperationsList {Array.<String>} 'List of operations required for transferring data from the oldRelease to the newRelease from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-c-im-nr-*_/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]' 
    */

    constructor(bequeathYourDataAndDieOperation, dataTransferOperationsList) {
        
        
        this['bequeath-your-data-and-die-operation'] = bequeathYourDataAndDieOperation;
        this['data-transfer-operations-list'] = dataTransferOperationsList;
        
    }

    /**
    * Constructs a <code>InlineResponse20016</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20016} obj Optional instance to populate.
    * @return {module:model/InlineResponse20016} The populated <code>InlineResponse20016</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20016();
                        
            
            if (data.hasOwnProperty('bequeath-your-data-and-die-operation')) {
                obj['bequeath-your-data-and-die-operation'] = ApiClient.convertToType(data['bequeath-your-data-and-die-operation'], 'String');
            }
            if (data.hasOwnProperty('data-transfer-operations-list')) {
                obj['data-transfer-operations-list'] = ApiClient.convertToType(data['data-transfer-operations-list'], ['String']);
            }
        }
        return obj;
    }

    /**
    * 'Operation for starting the handover process on the already existing application from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-s-im-000/layer-protocol=0/operation-server-interface-1-0:operation-server-interface-pac/operation-server-interface-capability/operation-name]' 
    * @member {String} bequeath-your-data-and-die-operation
    */
    'bequeath-your-data-and-die-operation' = undefined;
    /**
    * 'List of operations required for transferring data from the oldRelease to the newRelease from [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-op-c-im-nr-*_/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]' 
    * @member {Array.<String>} data-transfer-operations-list
    */
    'data-transfer-operations-list' = undefined;




}
