/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20042 model module.
* @module model/InlineResponse20042
* @version 1.0.1
*/
export default class InlineResponse20042 {
    /**
    * Constructs a new <code>InlineResponse20042</code>.
    * @alias module:model/InlineResponse20042
    * @class
    * @param httpServerInterface10ownerName {String} 
    */

    constructor(httpServerInterface10ownerName) {
        
        
        this['http-server-interface-1-0:owner-name'] = httpServerInterface10ownerName;
        
    }

    /**
    * Constructs a <code>InlineResponse20042</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20042} obj Optional instance to populate.
    * @return {module:model/InlineResponse20042} The populated <code>InlineResponse20042</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20042();
                        
            
            if (data.hasOwnProperty('http-server-interface-1-0:owner-name')) {
                obj['http-server-interface-1-0:owner-name'] = ApiClient.convertToType(data['http-server-interface-1-0:owner-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} http-server-interface-1-0:owner-name
    */
    'http-server-interface-1-0:owner-name' = undefined;




}
