/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse20047Tcpserverinterface10localaddress model module.
* @module model/InlineResponse20047Tcpserverinterface10localaddress
* @version 1.0.1
*/
export default class InlineResponse20047Tcpserverinterface10localaddress {
    /**
    * Constructs a new <code>InlineResponse20047Tcpserverinterface10localaddress</code>.
    * @alias module:model/InlineResponse20047Tcpserverinterface10localaddress
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>InlineResponse20047Tcpserverinterface10localaddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20047Tcpserverinterface10localaddress} obj Optional instance to populate.
    * @return {module:model/InlineResponse20047Tcpserverinterface10localaddress} The populated <code>InlineResponse20047Tcpserverinterface10localaddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20047Tcpserverinterface10localaddress();
                        
            
            if (data.hasOwnProperty('ipv-4-address')) {
                obj['ipv-4-address'] = ApiClient.convertToType(data['ipv-4-address'], 'String');
            }
            if (data.hasOwnProperty('domain-name')) {
                obj['domain-name'] = ApiClient.convertToType(data['domain-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} ipv-4-address
    */
    'ipv-4-address' = undefined;
    /**
    * @member {String} domain-name
    */
    'domain-name' = undefined;




}
