/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelObject from './ModelObject';

/**
* The LogicalTerminationPoint model module.
* @module model/LogicalTerminationPoint
* @version 1.0.1
*/
export default class LogicalTerminationPoint {
    /**
    * Constructs a new <code>LogicalTerminationPoint</code>.
    * @alias module:model/LogicalTerminationPoint
    * @class
    * @param uuid {String} 
    * @param ltpDirection {String} 
    * @param clientLtp {Array.<String>} 
    * @param serverLtp {Array.<String>} 
    * @param layerProtocol {Array.<module:model/ModelObject>} 
    */

    constructor(uuid, ltpDirection, clientLtp, serverLtp, layerProtocol) {
        
        
        this['uuid'] = uuid;
        this['ltp-direction'] = ltpDirection;
        this['client-ltp'] = clientLtp;
        this['server-ltp'] = serverLtp;
        this['layer-protocol'] = layerProtocol;
        
    }

    /**
    * Constructs a <code>LogicalTerminationPoint</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LogicalTerminationPoint} obj Optional instance to populate.
    * @return {module:model/LogicalTerminationPoint} The populated <code>LogicalTerminationPoint</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LogicalTerminationPoint();
                        
            
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('ltp-direction')) {
                obj['ltp-direction'] = ApiClient.convertToType(data['ltp-direction'], 'String');
            }
            if (data.hasOwnProperty('client-ltp')) {
                obj['client-ltp'] = ApiClient.convertToType(data['client-ltp'], ['String']);
            }
            if (data.hasOwnProperty('server-ltp')) {
                obj['server-ltp'] = ApiClient.convertToType(data['server-ltp'], ['String']);
            }
            if (data.hasOwnProperty('layer-protocol')) {
                obj['layer-protocol'] = ApiClient.convertToType(data['layer-protocol'], [OneOflogicalTerminationPointLayerProtocolItems]);
            }
        }
        return obj;
    }

    /**
    * @member {String} uuid
    */
    'uuid' = undefined;
    /**
    * @member {String} ltp-direction
    */
    'ltp-direction' = undefined;
    /**
    * @member {Array.<String>} client-ltp
    */
    'client-ltp' = undefined;
    /**
    * @member {Array.<String>} server-ltp
    */
    'server-ltp' = undefined;
    /**
    * @member {Array.<module:model/ModelObject>} layer-protocol
    */
    'layer-protocol' = undefined;




}
