/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The OneOfinlineResponse20012FailureTransactionLogsItems model module.
* @module model/OneOfinlineResponse20012FailureTransactionLogsItems
* @version 1.0.1
*/
export default class OneOfinlineResponse20012FailureTransactionLogsItems {
    /**
    * Constructs a new <code>OneOfinlineResponse20012FailureTransactionLogsItems</code>.
    * @alias module:model/OneOfinlineResponse20012FailureTransactionLogsItems
    * @class
    */

    constructor() {
    }

    /**
    * Constructs a <code>OneOfinlineResponse20012FailureTransactionLogsItems</code> from a plain JavaScript object, optionally creating a new instance.
    * Populates fields from both backup and restore failure log variants.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OneOfinlineResponse20012FailureTransactionLogsItems} obj Optional instance to populate.
    * @return {module:model/OneOfinlineResponse20012FailureTransactionLogsItems} The populated <code>OneOfinlineResponse20012FailureTransactionLogsItems</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneOfinlineResponse20012FailureTransactionLogsItems();

            if (data.hasOwnProperty('schedule-id')) {
                obj['schedule-id'] = ApiClient.convertToType(data['schedule-id'], 'String');
            }
            if (data.hasOwnProperty('schedule-name')) {
                obj['schedule-name'] = ApiClient.convertToType(data['schedule-name'], 'String');
            }
            if (data.hasOwnProperty('job-id')) {
                obj['job-id'] = ApiClient.convertToType(data['job-id'], 'String');
            }
            if (data.hasOwnProperty('job-name')) {
                obj['job-name'] = ApiClient.convertToType(data['job-name'], 'String');
            }
            if (data.hasOwnProperty('mount-name')) {
                obj['mount-name'] = ApiClient.convertToType(data['mount-name'], 'String');
            }
            if (data.hasOwnProperty('device-backup-status')) {
                obj['device-backup-status'] = ApiClient.convertToType(data['device-backup-status'], 'String');
            }
            if (data.hasOwnProperty('device-restore-status')) {
                obj['device-restore-status'] = ApiClient.convertToType(data['device-restore-status'], 'String');
            }
            if (data.hasOwnProperty('backup-job-id')) {
                obj['backup-job-id'] = ApiClient.convertToType(data['backup-job-id'], 'String');
            }
            if (data.hasOwnProperty('vendor')) {
                obj['vendor'] = ApiClient.convertToType(data['vendor'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('current-restore-step')) {
                obj['current-restore-step'] = ApiClient.convertToType(data['current-restore-step'], 'String');
            }
            if (data.hasOwnProperty('start-time')) {
                obj['start-time'] = ApiClient.convertToType(data['start-time'], 'Date');
            }
            if (data.hasOwnProperty('end-time')) {
                obj['end-time'] = ApiClient.convertToType(data['end-time'], 'Date');
            }
            if (data.hasOwnProperty('transaction-log')) {
                obj['transaction-log'] = ApiClient.convertToType(data['transaction-log'], [Object]);
            }
        }
        return obj;
    }

    'schedule-id' = undefined;
    'schedule-name' = undefined;
    'job-id' = undefined;
    'job-name' = undefined;
    'mount-name' = undefined;
    'device-backup-status' = undefined;
    'device-restore-status' = undefined;
    'backup-job-id' = undefined;
    'vendor' = undefined;
    'model' = undefined;
    'current-restore-step' = undefined;
    'start-time' = undefined;
    'end-time' = undefined;
    'transaction-log' = undefined;


}
