/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The OneOfBackupScheduleUpdate model module.
* @module model/OneOfBackupScheduleUpdate
* @version 1.0.1
*/
export default class OneOfBackupScheduleUpdate {
    /**
    * Constructs a new <code>OneOfBackupScheduleUpdate</code>.
    * @alias module:model/OneOfBackupScheduleUpdate
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OneOfBackupScheduleUpdate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OneOfBackupScheduleUpdate} obj Optional instance to populate.
    * @return {module:model/OneOfBackupScheduleUpdate} The populated <code>OneOfBackupScheduleUpdate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneOfBackupScheduleUpdate();
                        
            
        }
        return obj;
    }





}
