/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The OneOfinlineResponse20020CoreModel14profile model module.
* @module model/OneOfinlineResponse20020CoreModel14profile
* @version 1.0.1
*/
export default class OneOfinlineResponse20020CoreModel14profile {
    /**
    * Constructs a new <code>OneOfinlineResponse20020CoreModel14profile</code>.
    * @alias module:model/OneOfinlineResponse20020CoreModel14profile
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OneOfinlineResponse20020CoreModel14profile</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OneOfinlineResponse20020CoreModel14profile} obj Optional instance to populate.
    * @return {module:model/OneOfinlineResponse20020CoreModel14profile} The populated <code>OneOfinlineResponse20020CoreModel14profile</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneOfinlineResponse20020CoreModel14profile();
                        
            
        }
        return obj;
    }





}
