/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The V1registeryourselfHttpaddressIpaddress model module.
* @module model/V1registeryourselfHttpaddressIpaddress
* @version 1.0.1
*/
export default class V1registeryourselfHttpaddressIpaddress {
    /**
    * Constructs a new <code>V1registeryourselfHttpaddressIpaddress</code>.
    * @alias module:model/V1registeryourselfHttpaddressIpaddress
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>V1registeryourselfHttpaddressIpaddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/V1registeryourselfHttpaddressIpaddress} obj Optional instance to populate.
    * @return {module:model/V1registeryourselfHttpaddressIpaddress} The populated <code>V1registeryourselfHttpaddressIpaddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1registeryourselfHttpaddressIpaddress();
                        
            
            if (data.hasOwnProperty('ipv-4-address')) {
                obj['ipv-4-address'] = ApiClient.convertToType(data['ipv-4-address'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'If provided, own IPv4 address, which has to be documented (but not be directly used for formulating the callback) into the TcpServer with find [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-s-*_/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-protocol] == http update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-s-*_/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-address/ipv-4-address]' 
    * @member {String} ipv-4-address
    */
    'ipv-4-address' = undefined;




}
