/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1registeryourselfHttpaddressIpaddress from './V1registeryourselfHttpaddressIpaddress';

/**
* The V1registeryourselfHttpaddress model module.
* @module model/V1registeryourselfHttpaddress
* @version 1.0.1
*/
export default class V1registeryourselfHttpaddress {
    /**
    * Constructs a new <code>V1registeryourselfHttpaddress</code>.
    * @alias module:model/V1registeryourselfHttpaddress
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>V1registeryourselfHttpaddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/V1registeryourselfHttpaddress} obj Optional instance to populate.
    * @return {module:model/V1registeryourselfHttpaddress} The populated <code>V1registeryourselfHttpaddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1registeryourselfHttpaddress();
                        
            
            if (data.hasOwnProperty('ip-address')) {
                obj['ip-address'] = V1registeryourselfHttpaddressIpaddress.constructFromObject(data['ip-address']);
            }
            if (data.hasOwnProperty('domain-name')) {
                obj['domain-name'] = ApiClient.convertToType(data['domain-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/V1registeryourselfHttpaddressIpaddress} ip-address
    */
    'ip-address' = undefined;
    /**
    * 'If provided, own domain name, which has to be documented (but not be directly used for formulating the callback) into the TcpServer with find [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-s-*_/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-protocol] == http update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-s-*_/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-address/domain-name]' 
    * @member {String} domain-name
    */
    'domain-name' = undefined;




}
