/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress from './V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress';

/**
* The V1redirecttopologychangeinformationTopologyapplicationaddress model module.
* @module model/V1redirecttopologychangeinformationTopologyapplicationaddress
* @version 1.0.1
*/
export default class V1redirecttopologychangeinformationTopologyapplicationaddress {
    /**
    * Constructs a new <code>V1redirecttopologychangeinformationTopologyapplicationaddress</code>.
    * @alias module:model/V1redirecttopologychangeinformationTopologyapplicationaddress
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>V1redirecttopologychangeinformationTopologyapplicationaddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/V1redirecttopologychangeinformationTopologyapplicationaddress} obj Optional instance to populate.
    * @return {module:model/V1redirecttopologychangeinformationTopologyapplicationaddress} The populated <code>V1redirecttopologychangeinformationTopologyapplicationaddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1redirecttopologychangeinformationTopologyapplicationaddress();
                        
            
            if (data.hasOwnProperty('ip-address')) {
                obj['ip-address'] = V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress.constructFromObject(data['ip-address']);
            }
            if (data.hasOwnProperty('domain-name')) {
                obj['domain-name'] = ApiClient.convertToType(data['domain-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress} ip-address
    */
    'ip-address' = undefined;
    /**
    * 'Domain name of application that shall document the application layer topology update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-alt-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/domain-name]' 
    * @member {String} domain-name
    */
    'domain-name' = undefined;




}
