/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1registeryourselfHttpsaddressIpaddress from './V1registeryourselfHttpsaddressIpaddress';

/**
* The V1registeryourselfHttpsaddress model module.
* @module model/V1registeryourselfHttpsaddress
* @version 1.0.1
*/
export default class V1registeryourselfHttpsaddress {
    /**
    * Constructs a new <code>V1registeryourselfHttpsaddress</code>.
    * @alias module:model/V1registeryourselfHttpsaddress
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>V1registeryourselfHttpsaddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/V1registeryourselfHttpsaddress} obj Optional instance to populate.
    * @return {module:model/V1registeryourselfHttpsaddress} The populated <code>V1registeryourselfHttpsaddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1registeryourselfHttpsaddress();
                        
            
            if (data.hasOwnProperty('ip-address')) {
                obj['ip-address'] = V1registeryourselfHttpsaddressIpaddress.constructFromObject(data['ip-address']);
            }
            if (data.hasOwnProperty('domain-name')) {
                obj['domain-name'] = ApiClient.convertToType(data['domain-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/V1registeryourselfHttpsaddressIpaddress} ip-address
    */
    'ip-address' = undefined;
    /**
    * 'If provided, own domain name, which has to be documented (but not be directly used for formulating the callback) into the TcpServer with find [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-s-*_/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-protocol] == https update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-s-*_/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-address/domain-name]' 
    * @member {String} domain-name
    */
    'domain-name' = undefined;




}
