/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress model module.
* @module model/V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress
* @version 1.0.1
*/
export default class V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress {
    /**
    * Constructs a new <code>V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress</code>.
    * @alias module:model/V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress} obj Optional instance to populate.
    * @return {module:model/V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress} The populated <code>V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1redirecttopologychangeinformationTopologyapplicationaddressIpaddress();
                        
            
            if (data.hasOwnProperty('ipv-4-address')) {
                obj['ipv-4-address'] = ApiClient.convertToType(data['ipv-4-address'], 'String');
            }
        }
        return obj;
    }

    /**
    * 'IPv4 address of application that shall document the application layer topology update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-alt-2-1-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address]' 
    * @member {String} ipv-4-address
    */
    'ipv-4-address' = undefined;




}
