/**
 * BackupAndRestore
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1updateclientFutureaddressIpaddress from './V1updateclientFutureaddressIpaddress';

/**
* The V1updateclientFutureaddress model module.
* @module model/V1updateclientFutureaddress
* @version 1.0.1
*/
export default class V1updateclientFutureaddress {
    /**
    * Constructs a new <code>V1updateclientFutureaddress</code>.
    * @alias module:model/V1updateclientFutureaddress
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>V1updateclientFutureaddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/V1updateclientFutureaddress} obj Optional instance to populate.
    * @return {module:model/V1updateclientFutureaddress} The populated <code>V1updateclientFutureaddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1updateclientFutureaddress();
                        
            
            if (data.hasOwnProperty('ip-address')) {
                obj['ip-address'] = V1updateclientFutureaddressIpaddress.constructFromObject(data['ip-address']);
            }
            if (data.hasOwnProperty('domain-name')) {
                obj['domain-name'] = ApiClient.convertToType(data['domain-name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/V1updateclientFutureaddressIpaddress} ip-address
    */
    'ip-address' = undefined;
    /**
    * 'Future domain name of the application that has updated connection data update [/core-model-1-4:control-construct/logical-termination-point=bar-1-0-1-tcp-c-*_/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/domain-name]' 
    * @member {String} domain-name
    */
    'domain-name' = undefined;




}
