
const DEVICE_ATTR_VALUE_CHANGES = "device-attribute-value-changes";

const BACKUP_STATUS_TYPE_COMPLETED = "BACKUP_STATUS_TYPE_COMPLETED";
const BACKUP_STATUS_TYPE_ONGOING = "BACKUP_STATUS_TYPE_ONGOING";
const BACKUP_STATUS_TYPE_FAILED = "BACKUP_STATUS_TYPE_FAILED";

const PATH_STREAM_DEVICE = "/rests/notif/device?notificationType=device";

module.exports = {
    DEVICE_ATTR_VALUE_CHANGES,
    BACKUP_STATUS_TYPE_COMPLETED,
    BACKUP_STATUS_TYPE_ONGOING,
    BACKUP_STATUS_TYPE_FAILED,
    PATH_STREAM_DEVICE
}